const mongoose = require("mongoose");

const Category = require("../modules/categories/category.model");
const Product = require("../modules/products/product.model");
const Variant = require("../modules/products/variant.model");
const VariantUnit = require("../modules/products/variant_unit.model");

const CATEGORY_SLUGS = {
    mango: "tui-bao-trai-xoai",
    pomelo: "tui-bao-trai-buoi",
    guava: "tui-bao-trai-oi",
    dragonFruit: "tui-bao-trai-thanh-long",
    jackfruit: "tui-bao-trai-mit",
    grape: "tui-bao-trai-nho",
    longanLychee: "tui-bao-nhan-vai",
    banana: "tui-bao-trai-chuoi",
    custardApple: "tui-bao-trai-na-mang-cau",
    longVegetable: "tui-bao-rau-cu-qua-dai",
};

const productsData = [
    {
        name: "Túi bao trái xoài vải không dệt trắng 20x27cm",
        slug: "tui-bao-trai-xoai-vai-khong-det-trang-20x27cm",
        category_slug: CATEGORY_SLUGS.mango,
        brand: "Nguyen Lien",
        short_description: "Túi bao xoài loại phổ thông, có dây rút, phù hợp xoài đang phát triển.",
        description: "Sản phẩm dùng để bao trái xoài ngoài vườn, giúp hạn chế côn trùng, bụi bẩn và giảm trầy xước vỏ trái. Chất liệu vải không dệt trắng, thoáng khí, dễ sử dụng.",
        keywords: ["tui bao xoai", "bao trai xoai", "vai khong det", "tui day rut"],
        base_price: 45000,
        size_a: "20x27cm",
        size_b: "25x30cm",
        fabric_a: "Vải không dệt trắng",
        fabric_b: "Vải không dệt dày",
        stock_a: 6000,
        stock_b: 4200,
        sold_count: 135,
        rating_avg: 4.7,
        rating_count: 31,
    },
    {
        name: "Túi bao trái xoài Đài Loan size lớn 25x35cm",
        slug: "tui-bao-trai-xoai-dai-loan-size-lon-25x35cm",
        category_slug: CATEGORY_SLUGS.mango,
        brand: "Nguyen Lien",
        short_description: "Túi bao xoài size lớn, phù hợp xoài Đài Loan, xoài cát và xoài trái to.",
        description: "Dòng túi bao xoài kích thước lớn, dùng cho các giống xoài có trái dài hoặc phát triển mạnh. Có thể dùng trong vườn sản xuất quy mô nhỏ đến vừa.",
        keywords: ["tui bao xoai lon", "xoai dai loan", "xoai cat", "tui xoai"],
        base_price: 52000,
        size_a: "25x35cm",
        size_b: "28x38cm",
        fabric_a: "Vải không dệt trắng",
        fabric_b: "Vải không dệt 2 lớp",
        stock_a: 5000,
        stock_b: 3500,
        sold_count: 89,
        rating_avg: 4.6,
        rating_count: 18,
    },
    {
        name: "Túi bao xoài lưới thoáng khí dây rút",
        slug: "tui-bao-xoai-luoi-thoang-khi-day-rut",
        category_slug: CATEGORY_SLUGS.mango,
        brand: "Farm Bag",
        short_description: "Túi bao xoài dạng lưới, thoáng khí, dễ quan sát trái.",
        description: "Túi dạng lưới phù hợp nhu cầu bao trái nhưng vẫn cần độ thoáng và khả năng quan sát tình trạng trái trong quá trình chăm sóc.",
        keywords: ["tui luoi xoai", "tui bao xoai", "tui thoang khi", "day rut"],
        base_price: 39000,
        size_a: "20x30cm",
        size_b: "25x35cm",
        fabric_a: "Lưới nhựa trắng",
        fabric_b: "Lưới dày",
        stock_a: 7200,
        stock_b: 4600,
        sold_count: 76,
        rating_avg: 4.5,
        rating_count: 15,
    },
    {
        name: "Túi bao xoài giấy vàng chống nắng",
        slug: "tui-bao-xoai-giay-vang-chong-nang",
        category_slug: CATEGORY_SLUGS.mango,
        brand: "Green Farm",
        short_description: "Túi giấy bao xoài, phù hợp khu vực nắng nhiều.",
        description: "Dòng túi giấy giúp che phủ bề mặt trái, phù hợp vườn cần hạn chế ánh nắng trực tiếp tác động lên trái trong một số giai đoạn phát triển.",
        keywords: ["tui giay xoai", "bao xoai giay", "chong nang", "tui bao trai"],
        base_price: 48000,
        size_a: "20x28cm",
        size_b: "25x35cm",
        fabric_a: "Giấy kraft vàng",
        fabric_b: "Giấy kraft 2 lớp",
        stock_a: 3000,
        stock_b: 2200,
        sold_count: 42,
        rating_avg: 4.3,
        rating_count: 9,
    },
    {
        name: "Túi bao trái bưởi vải không dệt 30x35cm",
        slug: "tui-bao-trai-buoi-vai-khong-det-30x35cm",
        category_slug: CATEGORY_SLUGS.pomelo,
        brand: "Nguyen Lien",
        short_description: "Túi bao bưởi size lớn, phù hợp trái bưởi đang lớn.",
        description: "Túi bao bưởi giúp bảo vệ trái khỏi côn trùng và hạn chế trầy xước bề mặt vỏ. Kích thước rộng, dễ thao tác khi bao trái ngoài vườn.",
        keywords: ["tui bao buoi", "bao trai buoi", "tui size lon", "vai khong det"],
        base_price: 68000,
        size_a: "30x35cm",
        size_b: "35x40cm",
        fabric_a: "Vải không dệt trắng",
        fabric_b: "Vải không dệt dày",
        stock_a: 4200,
        stock_b: 2800,
        sold_count: 116,
        rating_avg: 4.8,
        rating_count: 26,
    },
    {
        name: "Túi bao bưởi da xanh size đại",
        slug: "tui-bao-buoi-da-xanh-size-dai",
        category_slug: CATEGORY_SLUGS.pomelo,
        brand: "Nguyen Lien",
        short_description: "Túi bao bưởi da xanh loại lớn, phù hợp trái to.",
        description: "Sản phẩm phù hợp bưởi da xanh, bưởi năm roi và các loại trái có kích thước lớn. Miệng túi rộng, dễ rút dây cố định.",
        keywords: ["buoi da xanh", "tui bao buoi", "tui bao trai lon", "tui day rut"],
        base_price: 76000,
        size_a: "35x40cm",
        size_b: "40x45cm",
        fabric_a: "Vải không dệt dày",
        fabric_b: "Vải không dệt 2 lớp",
        stock_a: 3200,
        stock_b: 1800,
        sold_count: 72,
        rating_avg: 4.6,
        rating_count: 17,
    },
    {
        name: "Túi lưới bao bưởi thoáng khí",
        slug: "tui-luoi-bao-buoi-thoang-khi",
        category_slug: CATEGORY_SLUGS.pomelo,
        brand: "Farm Bag",
        short_description: "Túi lưới bao bưởi, thoáng khí, phù hợp vườn cần quan sát trái.",
        description: "Túi lưới có độ thoáng cao, phù hợp nhu cầu bảo vệ trái nhưng vẫn cần quan sát màu sắc và kích thước trái trong quá trình chăm sóc.",
        keywords: ["tui luoi buoi", "bao buoi", "thoang khi", "tui bao trai cay"],
        base_price: 59000,
        size_a: "30x35cm",
        size_b: "35x40cm",
        fabric_a: "Lưới nhựa trắng",
        fabric_b: "Lưới dày",
        stock_a: 5000,
        stock_b: 3300,
        sold_count: 55,
        rating_avg: 4.4,
        rating_count: 12,
    },
    {
        name: "Túi bao trái ổi vải không dệt 15x20cm",
        slug: "tui-bao-trai-oi-vai-khong-det-15x20cm",
        category_slug: CATEGORY_SLUGS.guava,
        brand: "Nguyen Lien",
        short_description: "Túi bao ổi phổ thông, nhỏ gọn, dễ sử dụng.",
        description: "Túi bao trái ổi giúp hạn chế ruồi vàng, côn trùng và bụi bẩn. Kích thước phù hợp nhiều giống ổi phổ biến.",
        keywords: ["tui bao oi", "bao trai oi", "ruoi vang", "vai khong det"],
        base_price: 32000,
        size_a: "15x20cm",
        size_b: "18x22cm",
        fabric_a: "Vải không dệt trắng",
        fabric_b: "Vải không dệt dày",
        stock_a: 9000,
        stock_b: 6600,
        sold_count: 210,
        rating_avg: 4.8,
        rating_count: 49,
    },
    {
        name: "Túi bao ổi ruột đỏ dây rút",
        slug: "tui-bao-oi-ruot-do-day-rut",
        category_slug: CATEGORY_SLUGS.guava,
        brand: "Nguyen Lien",
        short_description: "Túi bao ổi có dây rút, phù hợp ổi ruột đỏ và ổi lê.",
        description: "Dòng túi bao ổi dành cho nhà vườn cần thao tác nhanh. Dây rút giúp cố định miệng túi tốt hơn khi treo trên cành.",
        keywords: ["oi ruot do", "tui bao oi", "tui day rut", "bao trai cay"],
        base_price: 35000,
        size_a: "16x22cm",
        size_b: "18x25cm",
        fabric_a: "Vải không dệt trắng",
        fabric_b: "Vải không dệt 2 lớp",
        stock_a: 8500,
        stock_b: 5200,
        sold_count: 146,
        rating_avg: 4.7,
        rating_count: 34,
    },
    {
        name: "Túi xốp lưới bao ổi chống trầy",
        slug: "tui-xop-luoi-bao-oi-chong-tray",
        category_slug: CATEGORY_SLUGS.guava,
        brand: "Green Farm",
        short_description: "Túi xốp lưới dùng cho ổi, hỗ trợ chống trầy vỏ trái.",
        description: "Túi xốp lưới mềm, phù hợp trái ổi cần hạn chế va chạm và trầy xước trong giai đoạn phát triển gần thu hoạch.",
        keywords: ["tui xop luoi", "bao oi", "chong tray", "tui bao trai"],
        base_price: 42000,
        size_a: "15x20cm",
        size_b: "18x22cm",
        fabric_a: "Xốp lưới trắng",
        fabric_b: "Xốp lưới dày",
        stock_a: 5600,
        stock_b: 4100,
        sold_count: 64,
        rating_avg: 4.5,
        rating_count: 13,
    },
    {
        name: "Túi bao thanh long vải không dệt 25x30cm",
        slug: "tui-bao-thanh-long-vai-khong-det-25x30cm",
        category_slug: CATEGORY_SLUGS.dragonFruit,
        brand: "Nguyen Lien",
        short_description: "Túi bao thanh long, kích thước vừa, dễ thao tác.",
        description: "Túi bao thanh long giúp bảo vệ trái trong quá trình phát triển, hạn chế bụi bẩn, côn trùng và trầy xước bề mặt.",
        keywords: ["tui bao thanh long", "bao thanh long", "vai khong det", "tui bao trai"],
        base_price: 50000,
        size_a: "25x30cm",
        size_b: "28x35cm",
        fabric_a: "Vải không dệt trắng",
        fabric_b: "Vải không dệt dày",
        stock_a: 4800,
        stock_b: 3400,
        sold_count: 98,
        rating_avg: 4.6,
        rating_count: 20,
    },
    {
        name: "Túi bao thanh long ruột đỏ size lớn",
        slug: "tui-bao-thanh-long-ruot-do-size-lon",
        category_slug: CATEGORY_SLUGS.dragonFruit,
        brand: "Farm Bag",
        short_description: "Túi bao thanh long size lớn cho trái phát triển mạnh.",
        description: "Phù hợp thanh long ruột đỏ hoặc trái có kích thước lớn. Chất liệu thoáng, dễ rút miệng túi.",
        keywords: ["thanh long ruot do", "tui bao thanh long", "size lon", "day rut"],
        base_price: 56000,
        size_a: "28x35cm",
        size_b: "30x40cm",
        fabric_a: "Vải không dệt trắng",
        fabric_b: "Vải không dệt 2 lớp",
        stock_a: 3900,
        stock_b: 2600,
        sold_count: 73,
        rating_avg: 4.4,
        rating_count: 14,
    },
    {
        name: "Túi giấy bao thanh long chống bụi",
        slug: "tui-giay-bao-thanh-long-chong-bui",
        category_slug: CATEGORY_SLUGS.dragonFruit,
        brand: "Green Farm",
        short_description: "Túi giấy bao thanh long, phù hợp nhu cầu che bụi và ánh nắng nhẹ.",
        description: "Túi giấy dùng cho thanh long, phù hợp vườn cần bảo vệ bề mặt trái và giảm tác động môi trường.",
        keywords: ["tui giay thanh long", "bao thanh long", "chong bui", "tui giay"],
        base_price: 47000,
        size_a: "25x30cm",
        size_b: "28x35cm",
        fabric_a: "Giấy kraft vàng",
        fabric_b: "Giấy kraft 2 lớp",
        stock_a: 2600,
        stock_b: 1900,
        sold_count: 36,
        rating_avg: 4.2,
        rating_count: 8,
    },
    {
        name: "Túi bao trái mít vải không dệt 45x55cm",
        slug: "tui-bao-trai-mit-vai-khong-det-45x55cm",
        category_slug: CATEGORY_SLUGS.jackfruit,
        brand: "Nguyen Lien",
        short_description: "Túi bao mít size lớn, phù hợp trái lớn và nặng.",
        description: "Túi bao mít có kích thước lớn, phù hợp các loại trái to. Chất liệu dày hơn để tăng độ bền khi sử dụng ngoài vườn.",
        keywords: ["tui bao mit", "bao trai mit", "tui size dai", "vai khong det"],
        base_price: 98000,
        size_a: "45x55cm",
        size_b: "50x60cm",
        fabric_a: "Vải không dệt dày",
        fabric_b: "Vải không dệt 2 lớp",
        stock_a: 1600,
        stock_b: 1100,
        sold_count: 48,
        rating_avg: 4.7,
        rating_count: 11,
    },
    {
        name: "Túi bao mít Thái dây rút chắc chắn",
        slug: "tui-bao-mit-thai-day-rut-chac-chan",
        category_slug: CATEGORY_SLUGS.jackfruit,
        brand: "Nguyen Lien",
        short_description: "Túi bao mít Thái, miệng rộng, dây rút chắc.",
        description: "Dùng cho mít Thái và các loại mít trái lớn. Thiết kế dây rút hỗ trợ cố định túi khi trái phát triển.",
        keywords: ["mit thai", "tui bao mit", "day rut", "tui trai lon"],
        base_price: 108000,
        size_a: "50x60cm",
        size_b: "55x65cm",
        fabric_a: "Vải không dệt dày",
        fabric_b: "Vải không dệt 2 lớp",
        stock_a: 1400,
        stock_b: 900,
        sold_count: 39,
        rating_avg: 4.6,
        rating_count: 10,
    },
    {
        name: "Túi lưới bao mít thoáng khí",
        slug: "tui-luoi-bao-mit-thoang-khi",
        category_slug: CATEGORY_SLUGS.jackfruit,
        brand: "Farm Bag",
        short_description: "Túi lưới bao mít, thoáng khí, kích thước rộng.",
        description: "Phù hợp vườn cần bao trái lớn nhưng vẫn giữ độ thoáng cao. Dễ quan sát trạng thái trái.",
        keywords: ["tui luoi mit", "bao mit", "thoang khi", "tui lon"],
        base_price: 89000,
        size_a: "45x55cm",
        size_b: "50x60cm",
        fabric_a: "Lưới nhựa trắng",
        fabric_b: "Lưới dày",
        stock_a: 1700,
        stock_b: 1200,
        sold_count: 27,
        rating_avg: 4.3,
        rating_count: 7,
    },
    {
        name: "Túi bao chùm nho vải không dệt 20x30cm",
        slug: "tui-bao-chum-nho-vai-khong-det-20x30cm",
        category_slug: CATEGORY_SLUGS.grape,
        brand: "Nguyen Lien",
        short_description: "Túi bao chùm nho, phù hợp bao theo chùm.",
        description: "Túi dùng cho nho hoặc các loại trái nhỏ mọc theo chùm. Kích thước vừa, dễ bao và tháo.",
        keywords: ["tui bao nho", "bao chum nho", "tui bao chum", "vai khong det"],
        base_price: 41000,
        size_a: "20x30cm",
        size_b: "25x35cm",
        fabric_a: "Vải không dệt trắng",
        fabric_b: "Vải không dệt dày",
        stock_a: 6200,
        stock_b: 4400,
        sold_count: 57,
        rating_avg: 4.5,
        rating_count: 13,
    },
    {
        name: "Túi giấy bao chùm nho chống côn trùng",
        slug: "tui-giay-bao-chum-nho-chong-con-trung",
        category_slug: CATEGORY_SLUGS.grape,
        brand: "Green Farm",
        short_description: "Túi giấy bao nho, che phủ tốt, phù hợp bao theo chùm.",
        description: "Dòng túi giấy dành cho chùm nho, giúp che chắn và hạn chế côn trùng tiếp xúc trực tiếp với trái.",
        keywords: ["tui giay nho", "bao chum nho", "chong con trung", "tui bao"],
        base_price: 45000,
        size_a: "20x30cm",
        size_b: "25x35cm",
        fabric_a: "Giấy kraft vàng",
        fabric_b: "Giấy kraft 2 lớp",
        stock_a: 2800,
        stock_b: 1900,
        sold_count: 31,
        rating_avg: 4.2,
        rating_count: 6,
    },
    {
        name: "Túi lưới bao chùm nho thoáng khí",
        slug: "tui-luoi-bao-chum-nho-thoang-khi",
        category_slug: CATEGORY_SLUGS.grape,
        brand: "Farm Bag",
        short_description: "Túi lưới bao nho, nhẹ, thoáng khí.",
        description: "Túi lưới dùng cho nho hoặc các chùm trái nhỏ. Phù hợp khi cần độ thoáng cao và dễ quan sát trái.",
        keywords: ["tui luoi nho", "bao chum nho", "thoang khi", "tui luoi"],
        base_price: 36000,
        size_a: "18x28cm",
        size_b: "22x32cm",
        fabric_a: "Lưới nhựa trắng",
        fabric_b: "Lưới mịn",
        stock_a: 5400,
        stock_b: 3800,
        sold_count: 44,
        rating_avg: 4.4,
        rating_count: 9,
    },
    {
        name: "Túi bao nhãn vải không dệt 25x35cm",
        slug: "tui-bao-nhan-vai-khong-det-25x35cm",
        category_slug: CATEGORY_SLUGS.longanLychee,
        brand: "Nguyen Lien",
        short_description: "Túi bao nhãn theo chùm, phù hợp vườn nhãn.",
        description: "Túi bao nhãn giúp bảo vệ chùm trái khỏi côn trùng và bụi bẩn. Dùng tốt cho nhãn xuồng, nhãn tiêu và các giống nhãn phổ biến.",
        keywords: ["tui bao nhan", "bao chum nhan", "nhan vai", "vai khong det"],
        base_price: 43000,
        size_a: "25x35cm",
        size_b: "30x40cm",
        fabric_a: "Vải không dệt trắng",
        fabric_b: "Vải không dệt dày",
        stock_a: 6400,
        stock_b: 4600,
        sold_count: 86,
        rating_avg: 4.6,
        rating_count: 19,
    },
    {
        name: "Túi bao trái vải theo chùm",
        slug: "tui-bao-trai-vai-theo-chum",
        category_slug: CATEGORY_SLUGS.longanLychee,
        brand: "Nguyen Lien",
        short_description: "Túi bao trái vải, phù hợp bao chùm trái.",
        description: "Sản phẩm dùng cho trái vải và các loại trái nhỏ mọc theo chùm. Thiết kế nhẹ, dễ thao tác khi bao nhiều chùm trên cây.",
        keywords: ["tui bao vai", "bao chum vai", "tui bao trai vai", "chum trai"],
        base_price: 44000,
        size_a: "25x35cm",
        size_b: "30x40cm",
        fabric_a: "Vải không dệt trắng",
        fabric_b: "Vải không dệt 2 lớp",
        stock_a: 5200,
        stock_b: 3100,
        sold_count: 52,
        rating_avg: 4.5,
        rating_count: 12,
    },
    {
        name: "Túi lưới bao nhãn vải thoáng khí",
        slug: "tui-luoi-bao-nhan-vai-thoang-khi",
        category_slug: CATEGORY_SLUGS.longanLychee,
        brand: "Farm Bag",
        short_description: "Túi lưới bao nhãn, vải, phù hợp chùm trái nhỏ.",
        description: "Túi lưới thoáng khí, dùng cho nhãn, vải hoặc các loại trái mọc theo chùm cần quan sát thường xuyên.",
        keywords: ["tui luoi nhan", "tui luoi vai", "bao chum", "thoang khi"],
        base_price: 37000,
        size_a: "25x35cm",
        size_b: "30x40cm",
        fabric_a: "Lưới nhựa trắng",
        fabric_b: "Lưới mịn",
        stock_a: 5900,
        stock_b: 4200,
        sold_count: 33,
        rating_avg: 4.3,
        rating_count: 8,
    },
    {
        name: "Túi bao buồng chuối vải không dệt 60x90cm",
        slug: "tui-bao-buong-chuoi-vai-khong-det-60x90cm",
        category_slug: CATEGORY_SLUGS.banana,
        brand: "Nguyen Lien",
        short_description: "Túi bao buồng chuối kích thước dài.",
        description: "Túi bao buồng chuối giúp che chắn buồng trái trong quá trình phát triển. Kích thước dài, phù hợp buồng chuối vừa.",
        keywords: ["tui bao chuoi", "bao buong chuoi", "tui dai", "vai khong det"],
        base_price: 115000,
        size_a: "60x90cm",
        size_b: "70x100cm",
        fabric_a: "Vải không dệt trắng",
        fabric_b: "Vải không dệt dày",
        stock_a: 1300,
        stock_b: 900,
        sold_count: 61,
        rating_avg: 4.7,
        rating_count: 14,
    },
    {
        name: "Túi bao buồng chuối size đại 80x120cm",
        slug: "tui-bao-buong-chuoi-size-dai-80x120cm",
        category_slug: CATEGORY_SLUGS.banana,
        brand: "Nguyen Lien",
        short_description: "Túi bao chuối size đại, phù hợp buồng lớn.",
        description: "Dòng túi bao chuối kích thước đại, dùng cho buồng chuối lớn hoặc vườn cần che phủ rộng.",
        keywords: ["tui bao chuoi dai", "bao buong chuoi", "size dai", "chuoi"],
        base_price: 145000,
        size_a: "80x120cm",
        size_b: "90x130cm",
        fabric_a: "Vải không dệt dày",
        fabric_b: "Vải không dệt 2 lớp",
        stock_a: 900,
        stock_b: 650,
        sold_count: 34,
        rating_avg: 4.5,
        rating_count: 8,
    },
    {
        name: "Túi lưới bao buồng chuối thoáng khí",
        slug: "tui-luoi-bao-buong-chuoi-thoang-khi",
        category_slug: CATEGORY_SLUGS.banana,
        brand: "Farm Bag",
        short_description: "Túi lưới bao buồng chuối, nhẹ và thoáng.",
        description: "Túi lưới kích thước dài, phù hợp vườn chuối cần độ thoáng cao và dễ quan sát buồng trái.",
        keywords: ["tui luoi chuoi", "bao chuoi", "buong chuoi", "thoang khi"],
        base_price: 99000,
        size_a: "60x90cm",
        size_b: "70x100cm",
        fabric_a: "Lưới nhựa trắng",
        fabric_b: "Lưới dày",
        stock_a: 1500,
        stock_b: 1000,
        sold_count: 29,
        rating_avg: 4.2,
        rating_count: 7,
    },
    {
        name: "Túi bao trái na vải không dệt 18x25cm",
        slug: "tui-bao-trai-na-vai-khong-det-18x25cm",
        category_slug: CATEGORY_SLUGS.custardApple,
        brand: "Nguyen Lien",
        short_description: "Túi bao trái na, kích thước vừa, có dây rút.",
        description: "Túi bao trái na giúp hạn chế côn trùng tiếp xúc với trái, phù hợp giai đoạn trái đang lớn.",
        keywords: ["tui bao na", "bao trai na", "mang cau", "vai khong det"],
        base_price: 38000,
        size_a: "18x25cm",
        size_b: "20x28cm",
        fabric_a: "Vải không dệt trắng",
        fabric_b: "Vải không dệt dày",
        stock_a: 5800,
        stock_b: 3900,
        sold_count: 51,
        rating_avg: 4.5,
        rating_count: 11,
    },
    {
        name: "Túi bao mãng cầu dai size lớn",
        slug: "tui-bao-mang-cau-dai-size-lon",
        category_slug: CATEGORY_SLUGS.custardApple,
        brand: "Nguyen Lien",
        short_description: "Túi bao mãng cầu dai, phù hợp trái lớn.",
        description: "Sản phẩm dùng cho mãng cầu dai và các loại trái có bề mặt dễ bị côn trùng tấn công. Chất liệu thoáng, nhẹ.",
        keywords: ["tui bao mang cau", "mang cau dai", "tui size lon", "bao trai"],
        base_price: 46000,
        size_a: "22x30cm",
        size_b: "25x35cm",
        fabric_a: "Vải không dệt trắng",
        fabric_b: "Vải không dệt 2 lớp",
        stock_a: 4100,
        stock_b: 2700,
        sold_count: 37,
        rating_avg: 4.4,
        rating_count: 9,
    },
    {
        name: "Túi xốp lưới bao na chống trầy",
        slug: "tui-xop-luoi-bao-na-chong-tray",
        category_slug: CATEGORY_SLUGS.custardApple,
        brand: "Green Farm",
        short_description: "Túi xốp lưới bao na, hỗ trợ giảm trầy xước.",
        description: "Túi xốp lưới mềm dùng cho na, mãng cầu hoặc trái có bề mặt dễ trầy. Phù hợp nhu cầu bảo vệ vật lý nhẹ.",
        keywords: ["tui xop luoi", "bao na", "mang cau", "chong tray"],
        base_price: 49000,
        size_a: "18x25cm",
        size_b: "22x30cm",
        fabric_a: "Xốp lưới trắng",
        fabric_b: "Xốp lưới dày",
        stock_a: 3300,
        stock_b: 2200,
        sold_count: 22,
        rating_avg: 4.1,
        rating_count: 5,
    },
    {
        name: "Túi bao mướp dài vải không dệt 15x45cm",
        slug: "tui-bao-muop-dai-vai-khong-det-15x45cm",
        category_slug: CATEGORY_SLUGS.longVegetable,
        brand: "Nguyen Lien",
        short_description: "Túi bao mướp dáng dài, phù hợp quả dài.",
        description: "Túi bao cho mướp, bầu, bí và các loại quả dáng dài. Thiết kế chiều dài lớn hơn túi trái cây thông thường.",
        keywords: ["tui bao muop", "tui bao qua dai", "bau bi", "vai khong det"],
        base_price: 53000,
        size_a: "15x45cm",
        size_b: "18x50cm",
        fabric_a: "Vải không dệt trắng",
        fabric_b: "Vải không dệt dày",
        stock_a: 4300,
        stock_b: 3000,
        sold_count: 68,
        rating_avg: 4.6,
        rating_count: 15,
    },
    {
        name: "Túi bao khổ qua vải không dệt 12x30cm",
        slug: "tui-bao-kho-qua-vai-khong-det-12x30cm",
        category_slug: CATEGORY_SLUGS.longVegetable,
        brand: "Nguyen Lien",
        short_description: "Túi bao khổ qua nhỏ gọn, dễ bao trái.",
        description: "Túi bao khổ qua giúp che chắn quả trong quá trình phát triển. Kích thước nhỏ, phù hợp quả dáng dài vừa.",
        keywords: ["tui bao kho qua", "kho qua", "qua dai", "vai khong det"],
        base_price: 36000,
        size_a: "12x30cm",
        size_b: "15x35cm",
        fabric_a: "Vải không dệt trắng",
        fabric_b: "Vải không dệt dày",
        stock_a: 6500,
        stock_b: 4700,
        sold_count: 74,
        rating_avg: 4.5,
        rating_count: 16,
    },
    {
        name: "Túi bao bầu bí size dài",
        slug: "tui-bao-bau-bi-size-dai",
        category_slug: CATEGORY_SLUGS.longVegetable,
        brand: "Farm Bag",
        short_description: "Túi bao bầu bí dáng dài, kích thước rộng.",
        description: "Dòng túi bao phù hợp bầu, bí, mướp và nhóm rau củ quả dáng dài. Dễ sử dụng trong vườn rau màu.",
        keywords: ["tui bao bau", "tui bao bi", "qua dai", "rau cu qua"],
        base_price: 58000,
        size_a: "18x50cm",
        size_b: "20x60cm",
        fabric_a: "Vải không dệt trắng",
        fabric_b: "Vải không dệt 2 lớp",
        stock_a: 3600,
        stock_b: 2400,
        sold_count: 41,
        rating_avg: 4.3,
        rating_count: 9,
    },
    {
        name: "Túi bao xoài mini 18x25cm",
        slug: "tui-bao-xoai-mini-18x25cm",
        category_slug: CATEGORY_SLUGS.mango,
        brand: "Nguyen Lien",
        short_description: "Túi bao xoài mini, phù hợp trái nhỏ hoặc giai đoạn đầu.",
        description: "Túi bao xoài kích thước nhỏ, dùng khi trái còn nhỏ hoặc cho giống xoài trái vừa.",
        keywords: ["tui bao xoai mini", "xoai nho", "bao xoai", "tui nho"],
        base_price: 34000,
        size_a: "18x25cm",
        size_b: "20x27cm",
        fabric_a: "Vải không dệt trắng",
        fabric_b: "Lưới nhựa trắng",
        stock_a: 7000,
        stock_b: 5100,
        sold_count: 63,
        rating_avg: 4.4,
        rating_count: 13,
    },
    {
        name: "Túi bao bưởi giấy kraft 35x40cm",
        slug: "tui-bao-buoi-giay-kraft-35x40cm",
        category_slug: CATEGORY_SLUGS.pomelo,
        brand: "Green Farm",
        short_description: "Túi giấy kraft bao bưởi, che phủ tốt.",
        description: "Túi giấy kraft dành cho bưởi và trái lớn, phù hợp nhu cầu che chắn ánh sáng và bụi bẩn.",
        keywords: ["tui giay buoi", "giay kraft", "bao buoi", "tui trai lon"],
        base_price: 72000,
        size_a: "35x40cm",
        size_b: "40x45cm",
        fabric_a: "Giấy kraft vàng",
        fabric_b: "Giấy kraft 2 lớp",
        stock_a: 2300,
        stock_b: 1500,
        sold_count: 21,
        rating_avg: 4.1,
        rating_count: 5,
    },
    {
        name: "Túi bao ổi mini 12x18cm",
        slug: "tui-bao-oi-mini-12x18cm",
        category_slug: CATEGORY_SLUGS.guava,
        brand: "Nguyen Lien",
        short_description: "Túi bao ổi nhỏ, dùng cho trái non hoặc giống ổi nhỏ.",
        description: "Kích thước nhỏ gọn, phù hợp ổi trái nhỏ hoặc giai đoạn trái còn non.",
        keywords: ["tui bao oi mini", "oi non", "tui nho", "bao oi"],
        base_price: 28000,
        size_a: "12x18cm",
        size_b: "15x20cm",
        fabric_a: "Vải không dệt trắng",
        fabric_b: "Lưới mịn",
        stock_a: 7800,
        stock_b: 5300,
        sold_count: 59,
        rating_avg: 4.3,
        rating_count: 12,
    },
    {
        name: "Túi bao thanh long lưới trắng",
        slug: "tui-bao-thanh-long-luoi-trang",
        category_slug: CATEGORY_SLUGS.dragonFruit,
        brand: "Farm Bag",
        short_description: "Túi lưới trắng bao thanh long, thoáng khí.",
        description: "Dùng cho thanh long cần độ thoáng cao, dễ quan sát màu sắc và kích thước trái.",
        keywords: ["tui luoi thanh long", "bao thanh long", "luoi trang", "thoang khi"],
        base_price: 43000,
        size_a: "25x30cm",
        size_b: "28x35cm",
        fabric_a: "Lưới nhựa trắng",
        fabric_b: "Lưới dày",
        stock_a: 3900,
        stock_b: 2600,
        sold_count: 18,
        rating_avg: 4.0,
        rating_count: 4,
    },
    {
        name: "Túi bao mít giấy kraft size lớn",
        slug: "tui-bao-mit-giay-kraft-size-lon",
        category_slug: CATEGORY_SLUGS.jackfruit,
        brand: "Green Farm",
        short_description: "Túi giấy kraft cho mít, kích thước lớn.",
        description: "Túi giấy kraft dùng cho mít hoặc trái rất lớn, hỗ trợ che bụi và ánh nắng nhẹ.",
        keywords: ["tui giay mit", "giay kraft", "bao mit", "tui size lon"],
        base_price: 95000,
        size_a: "45x55cm",
        size_b: "50x60cm",
        fabric_a: "Giấy kraft vàng",
        fabric_b: "Giấy kraft 2 lớp",
        stock_a: 1100,
        stock_b: 750,
        sold_count: 12,
        rating_avg: 4.0,
        rating_count: 3,
        status: "INACTIVE",
    },
    {
        name: "Túi bao chùm nho mini 18x25cm",
        slug: "tui-bao-chum-nho-mini-18x25cm",
        category_slug: CATEGORY_SLUGS.grape,
        brand: "Nguyen Lien",
        short_description: "Túi bao chùm nho nhỏ, phù hợp chùm vừa.",
        description: "Túi bao chùm nho kích thước nhỏ, phù hợp chùm trái vừa hoặc vườn thử nghiệm.",
        keywords: ["tui bao nho mini", "chum nho", "tui nho", "bao nho"],
        base_price: 32000,
        size_a: "18x25cm",
        size_b: "20x30cm",
        fabric_a: "Vải không dệt trắng",
        fabric_b: "Lưới mịn",
        stock_a: 4200,
        stock_b: 3000,
        sold_count: 24,
        rating_avg: 4.2,
        rating_count: 5,
    },
    {
        name: "Túi bao nhãn giấy kraft",
        slug: "tui-bao-nhan-giay-kraft",
        category_slug: CATEGORY_SLUGS.longanLychee,
        brand: "Green Farm",
        short_description: "Túi giấy kraft bao chùm nhãn.",
        description: "Túi giấy kraft dùng cho nhãn, vải hoặc chùm trái nhỏ cần che phủ tốt.",
        keywords: ["tui giay nhan", "bao chum nhan", "giay kraft", "nhan vai"],
        base_price: 42000,
        size_a: "25x35cm",
        size_b: "30x40cm",
        fabric_a: "Giấy kraft vàng",
        fabric_b: "Giấy kraft 2 lớp",
        stock_a: 1900,
        stock_b: 1200,
        sold_count: 14,
        rating_avg: 4.1,
        rating_count: 4,
    },
    {
        name: "Túi bao chuối giấy kraft",
        slug: "tui-bao-chuoi-giay-kraft",
        category_slug: CATEGORY_SLUGS.banana,
        brand: "Green Farm",
        short_description: "Túi giấy kraft bao buồng chuối.",
        description: "Dùng cho buồng chuối cần che chắn bụi và ánh nắng nhẹ. Kích thước dài phù hợp treo ngoài vườn.",
        keywords: ["tui giay chuoi", "bao buong chuoi", "giay kraft", "tui dai"],
        base_price: 125000,
        size_a: "60x90cm",
        size_b: "70x100cm",
        fabric_a: "Giấy kraft vàng",
        fabric_b: "Giấy kraft 2 lớp",
        stock_a: 800,
        stock_b: 500,
        sold_count: 9,
        rating_avg: 3.9,
        rating_count: 3,
        status: "INACTIVE",
    },
    {
        name: "Túi bao mãng cầu xiêm 30x40cm",
        slug: "tui-bao-mang-cau-xiem-30x40cm",
        category_slug: CATEGORY_SLUGS.custardApple,
        brand: "Nguyen Lien",
        short_description: "Túi bao mãng cầu xiêm size lớn.",
        description: "Túi bao mãng cầu xiêm, kích thước lớn hơn túi bao na thông thường, phù hợp trái to.",
        keywords: ["mang cau xiem", "tui bao mang cau", "tui size lon", "bao trai"],
        base_price: 62000,
        size_a: "30x40cm",
        size_b: "35x45cm",
        fabric_a: "Vải không dệt trắng",
        fabric_b: "Vải không dệt dày",
        stock_a: 2400,
        stock_b: 1600,
        sold_count: 19,
        rating_avg: 4.2,
        rating_count: 5,
    },
    {
        name: "Túi bao dưa leo 10x28cm",
        slug: "tui-bao-dua-leo-10x28cm",
        category_slug: CATEGORY_SLUGS.longVegetable,
        brand: "Nguyen Lien",
        short_description: "Túi bao dưa leo nhỏ, dáng dài.",
        description: "Túi bao dưa leo và quả dáng dài nhỏ. Phù hợp vườn rau màu cần bao quả để hạn chế côn trùng.",
        keywords: ["tui bao dua leo", "dua leo", "qua dai", "tui nho"],
        base_price: 30000,
        size_a: "10x28cm",
        size_b: "12x32cm",
        fabric_a: "Vải không dệt trắng",
        fabric_b: "Lưới mịn",
        stock_a: 6200,
        stock_b: 4400,
        sold_count: 47,
        rating_avg: 4.4,
        rating_count: 10,
    },
    {
        name: "Túi bao xoài cao cấp 2 lớp",
        slug: "tui-bao-xoai-cao-cap-2-lop",
        category_slug: CATEGORY_SLUGS.mango,
        brand: "Nguyen Lien Premium",
        short_description: "Túi bao xoài 2 lớp, dày hơn dòng phổ thông.",
        description: "Dòng túi bao xoài cao cấp, chất liệu dày hơn, phù hợp nhà vườn cần độ bền cao hơn khi sử dụng ngoài trời.",
        keywords: ["tui bao xoai cao cap", "2 lop", "vai khong det", "tui day"],
        base_price: 66000,
        size_a: "25x35cm",
        size_b: "28x38cm",
        fabric_a: "Vải không dệt 2 lớp",
        fabric_b: "Vải không dệt dày",
        stock_a: 2600,
        stock_b: 1800,
        sold_count: 26,
        rating_avg: 4.5,
        rating_count: 6,
    },
    {
        name: "Túi bao bưởi cao cấp 2 lớp",
        slug: "tui-bao-buoi-cao-cap-2-lop",
        category_slug: CATEGORY_SLUGS.pomelo,
        brand: "Nguyen Lien Premium",
        short_description: "Túi bao bưởi 2 lớp, size lớn.",
        description: "Dòng túi bao bưởi cao cấp, phù hợp trái lớn và nhu cầu bảo vệ tốt hơn dòng phổ thông.",
        keywords: ["tui bao buoi cao cap", "2 lop", "tui size lon", "buoi"],
        base_price: 88000,
        size_a: "35x40cm",
        size_b: "40x45cm",
        fabric_a: "Vải không dệt 2 lớp",
        fabric_b: "Vải không dệt dày",
        stock_a: 1900,
        stock_b: 1200,
        sold_count: 18,
        rating_avg: 4.4,
        rating_count: 5,
    },
    {
        name: "Túi bao ổi cao cấp 2 lớp",
        slug: "tui-bao-oi-cao-cap-2-lop",
        category_slug: CATEGORY_SLUGS.guava,
        brand: "Nguyen Lien Premium",
        short_description: "Túi bao ổi 2 lớp, chắc hơn dòng phổ thông.",
        description: "Dòng túi bao ổi cao cấp, phù hợp nhà vườn cần túi dày hơn và giữ form tốt hơn.",
        keywords: ["tui bao oi cao cap", "2 lop", "bao oi", "tui day"],
        base_price: 46000,
        size_a: "16x22cm",
        size_b: "18x25cm",
        fabric_a: "Vải không dệt 2 lớp",
        fabric_b: "Vải không dệt dày",
        stock_a: 3300,
        stock_b: 2300,
        sold_count: 22,
        rating_avg: 4.5,
        rating_count: 5,
    },
    {
        name: "Túi bao thanh long cao cấp",
        slug: "tui-bao-thanh-long-cao-cap",
        category_slug: CATEGORY_SLUGS.dragonFruit,
        brand: "Nguyen Lien Premium",
        short_description: "Túi bao thanh long chất liệu dày.",
        description: "Dòng túi bao thanh long chất liệu dày, phù hợp nhu cầu sử dụng bền hơn ngoài vườn.",
        keywords: ["tui bao thanh long cao cap", "2 lop", "thanh long", "tui day"],
        base_price: 62000,
        size_a: "28x35cm",
        size_b: "30x40cm",
        fabric_a: "Vải không dệt 2 lớp",
        fabric_b: "Vải không dệt dày",
        stock_a: 2100,
        stock_b: 1500,
        sold_count: 13,
        rating_avg: 4.2,
        rating_count: 4,
    },
    {
        name: "Túi bao mít cao cấp size đại",
        slug: "tui-bao-mit-cao-cap-size-dai",
        category_slug: CATEGORY_SLUGS.jackfruit,
        brand: "Nguyen Lien Premium",
        short_description: "Túi bao mít cao cấp, size đại.",
        description: "Túi bao mít size đại, chất liệu dày, phù hợp trái lớn và thời gian treo ngoài vườn dài hơn.",
        keywords: ["tui bao mit cao cap", "size dai", "mit", "tui day"],
        base_price: 125000,
        size_a: "55x65cm",
        size_b: "60x70cm",
        fabric_a: "Vải không dệt 2 lớp",
        fabric_b: "Vải không dệt dày",
        stock_a: 700,
        stock_b: 450,
        sold_count: 8,
        rating_avg: 4.1,
        rating_count: 3,
        status: "INACTIVE",
    },
    {
        name: "Túi bao nho cao cấp chống bụi",
        slug: "tui-bao-nho-cao-cap-chong-bui",
        category_slug: CATEGORY_SLUGS.grape,
        brand: "Nguyen Lien Premium",
        short_description: "Túi bao nho cao cấp, che bụi tốt.",
        description: "Dòng túi bao chùm nho chất liệu dày hơn, phù hợp vườn cần bảo vệ chùm trái tốt hơn.",
        keywords: ["tui bao nho cao cap", "chong bui", "nho", "bao chum"],
        base_price: 52000,
        size_a: "22x32cm",
        size_b: "25x35cm",
        fabric_a: "Vải không dệt 2 lớp",
        fabric_b: "Vải không dệt dày",
        stock_a: 1900,
        stock_b: 1300,
        sold_count: 11,
        rating_avg: 4.0,
        rating_count: 3,
    },
    {
        name: "Túi bao nhãn vải cao cấp",
        slug: "tui-bao-nhan-vai-cao-cap",
        category_slug: CATEGORY_SLUGS.longanLychee,
        brand: "Nguyen Lien Premium",
        short_description: "Túi bao nhãn, vải cao cấp, chất liệu dày.",
        description: "Túi bao chùm nhãn vải chất liệu dày, dùng cho vườn cần bảo vệ chùm trái tốt hơn.",
        keywords: ["tui bao nhan cao cap", "tui bao vai", "bao chum", "2 lop"],
        base_price: 54000,
        size_a: "30x40cm",
        size_b: "35x45cm",
        fabric_a: "Vải không dệt 2 lớp",
        fabric_b: "Vải không dệt dày",
        stock_a: 1700,
        stock_b: 1100,
        sold_count: 10,
        rating_avg: 4.0,
        rating_count: 3,
    },
    {
        name: "Túi bao chuối cao cấp 2 lớp",
        slug: "tui-bao-chuoi-cao-cap-2-lop",
        category_slug: CATEGORY_SLUGS.banana,
        brand: "Nguyen Lien Premium",
        short_description: "Túi bao buồng chuối cao cấp, chất liệu dày.",
        description: "Túi bao buồng chuối chất liệu dày, phù hợp buồng lớn và thời gian sử dụng ngoài vườn lâu hơn.",
        keywords: ["tui bao chuoi cao cap", "2 lop", "buong chuoi", "tui dai"],
        base_price: 165000,
        size_a: "80x120cm",
        size_b: "90x130cm",
        fabric_a: "Vải không dệt 2 lớp",
        fabric_b: "Vải không dệt dày",
        stock_a: 520,
        stock_b: 350,
        sold_count: 7,
        rating_avg: 4.0,
        rating_count: 2,
        status: "INACTIVE",
    },
    {
        name: "Túi bao na cao cấp 2 lớp",
        slug: "tui-bao-na-cao-cap-2-lop",
        category_slug: CATEGORY_SLUGS.custardApple,
        brand: "Nguyen Lien Premium",
        short_description: "Túi bao na chất liệu dày, có dây rút.",
        description: "Dòng túi bao na cao cấp, phù hợp trái dễ trầy và cần túi dày hơn dòng phổ thông.",
        keywords: ["tui bao na cao cap", "2 lop", "mang cau", "tui day"],
        base_price: 56000,
        size_a: "22x30cm",
        size_b: "25x35cm",
        fabric_a: "Vải không dệt 2 lớp",
        fabric_b: "Vải không dệt dày",
        stock_a: 1600,
        stock_b: 1000,
        sold_count: 9,
        rating_avg: 4.1,
        rating_count: 3,
    },
    {
        name: "Túi bao rau củ quả dài cao cấp",
        slug: "tui-bao-rau-cu-qua-dai-cao-cap",
        category_slug: CATEGORY_SLUGS.longVegetable,
        brand: "Nguyen Lien Premium",
        short_description: "Túi bao rau củ quả dáng dài, chất liệu dày.",
        description: "Dòng túi bao cao cấp cho mướp, bầu, bí, dưa leo, khổ qua và các loại quả dáng dài.",
        keywords: ["tui bao rau cu", "qua dai", "2 lop", "tui dai"],
        base_price: 69000,
        size_a: "18x50cm",
        size_b: "20x60cm",
        fabric_a: "Vải không dệt 2 lớp",
        fabric_b: "Vải không dệt dày",
        stock_a: 1800,
        stock_b: 1200,
        sold_count: 12,
        rating_avg: 4.1,
        rating_count: 3,
        status: "INACTIVE",
    },
];

const toSkuPart = (value) => {
    return value
        .normalize("NFD")
        .replace(/[\u0300-\u036f]/g, "")
        .replace(/đ/g, "d")
        .replace(/Đ/g, "D")
        .toUpperCase()
        .replace(/[^A-Z0-9]+/g, "-")
        .replace(/^-+|-+$/g, "")
        .slice(0, 36);
};

const buildPriceTiers = (basePrice) => {
    return [
        {
            min_qty: 1,
            max_qty: 4,
            unit_price: basePrice,
        },
        {
            min_qty: 5,
            max_qty: 9,
            unit_price: Math.round(basePrice * 0.94),
        },
        {
            min_qty: 10,
            max_qty: null,
            unit_price: Math.round(basePrice * 0.88),
        },
    ];
};

const buildUnits = (basePrice) => {
    return [
        {
            unit_type: "PACK",
            display_name: "Gói 100 cái",
            pack_size: 100,
            price_tiers: buildPriceTiers(basePrice),
            min_order_qty: 1,
            max_order_qty: null,
            qty_step: 1,
            is_default: true,
            currency: "VND",
        },
        {
            unit_type: "BOX",
            display_name: "Thùng 1000 cái",
            pack_size: 1000,
            price_tiers: buildPriceTiers(Math.round(basePrice * 9.2)),
            min_order_qty: 1,
            max_order_qty: null,
            qty_step: 1,
            is_default: false,
            currency: "VND",
        },
    ];
};

const buildVariants = (product) => {
    return [
        {
            sku: `NL-${toSkuPart(product.slug)}-A`,
            size: product.size_a,
            fabric_type: product.fabric_a,
            stock: {
                available: product.stock_a,
                reserved: 0,
                sold: product.sold_count || 0,
            },
            units: buildUnits(product.base_price),
        },
        {
            sku: `NL-${toSkuPart(product.slug)}-B`,
            size: product.size_b,
            fabric_type: product.fabric_b,
            stock: {
                available: product.stock_b,
                reserved: 0,
                sold: Math.floor((product.sold_count || 0) * 0.45),
            },
            units: buildUnits(Math.round(product.base_price * 1.18)),
        },
    ];
};

const seedProducts = async () => {
    console.log("== Seeding products ==");

    const categories = await Category.find({
        slug: { $in: Object.values(CATEGORY_SLUGS) },
        status: "ACTIVE",
    }).select("_id slug");

    const categoryMap = new Map(
        categories.map((category) => [category.slug, category._id])
    );

    const missingCategorySlugs = Object.values(CATEGORY_SLUGS).filter(
        (slug) => !categoryMap.has(slug)
    );

    if (missingCategorySlugs.length > 0) {
        throw new Error(
            `Missing categories. Run "npm run seed:categories" first. Missing: ${missingCategorySlugs.join(", ")}`
        );
    }

    for (const item of productsData) {
        const categoryId = categoryMap.get(item.category_slug);

        const existingProduct = await Product.findOne(
            { slug: item.slug },
            null,
            { includeDeleted: true }
        );

        let product;

        const productPayload = {
            name: item.name,
            slug: item.slug,
            category_id: categoryId,
            brand: item.brand,
            short_description: item.short_description,
            description: item.description,
            images: [],
            search_keywords: item.keywords,
            rating_avg: item.rating_avg || 0,
            rating_count: item.rating_count || 0,
            sold_count: item.sold_count || 0,
            status: item.status || "ACTIVE",
            is_deleted: false,
            deleted_at: null,
        };

        if (existingProduct) {
            await Product.updateOne(
                { _id: existingProduct._id },
                { $set: productPayload },
                { runValidators: true }
            );

            product = await Product.findById(existingProduct._id);

            console.log(`↻ Updated product: ${item.slug}`);
        } else {
            product = await Product.create(productPayload);

            console.log(`✓ Created product: ${item.slug}`);
        }

        const variants = buildVariants(item);

        for (const variantData of variants) {
            const existingVariant = await Variant.findOne(
                {
                    product_id: product._id,
                    size: variantData.size,
                    fabric_type: variantData.fabric_type,
                },
                null,
                { includeDeleted: true }
            );

            let variant;

            const variantPayload = {
                product_id: product._id,
                sku: variantData.sku,
                size: variantData.size,
                fabric_type: variantData.fabric_type,
                stock: variantData.stock,
                status: product.status,
                is_deleted: false,
                deleted_at: null,
            };

            if (existingVariant) {
                await Variant.updateOne(
                    { _id: existingVariant._id },
                    { $set: variantPayload },
                    { runValidators: true }
                );

                variant = await Variant.findById(existingVariant._id);

                console.log(`  ↻ Updated variant: ${variantData.sku}`);
            } else {
                variant = await Variant.create(variantPayload);

                console.log(`  ✓ Created variant: ${variantData.sku}`);
            }

            for (const unitData of variantData.units) {
                VariantUnit.validatePriceTiers(unitData.price_tiers);

                const existingUnit = await VariantUnit.findOne({
                    variant_id: variant._id,
                    pack_size: unitData.pack_size,
                });

                const unitPayload = {
                    variant_id: variant._id,
                    unit_type: unitData.unit_type,
                    display_name: unitData.display_name,
                    pack_size: unitData.pack_size,
                    price_tiers: unitData.price_tiers,
                    min_order_qty: unitData.min_order_qty,
                    max_order_qty: unitData.max_order_qty,
                    qty_step: unitData.qty_step,
                    is_default: unitData.is_default,
                    currency: unitData.currency,
                };

                if (existingUnit) {
                    await VariantUnit.updateOne(
                        { _id: existingUnit._id },
                        { $set: unitPayload },
                        { runValidators: true }
                    );

                    console.log(
                        `    ↻ Updated unit: ${unitData.display_name}`
                    );
                } else {
                    await VariantUnit.create(unitPayload);

                    console.log(
                        `    ✓ Created unit: ${unitData.display_name}`
                    );
                }
            }

            await Variant.updatePriceCache(variant._id);
        }

        await Product.updatePriceCache(product._id);
    }

    console.log("✓ Products seeding completed");
};

if (require.main === module) {
    require("dotenv").config();

    const MONGODB_URI = process.env.MONGO_URI;

    if (!MONGODB_URI) {
        throw new Error("Missing MONGO_URI in .env");
    }

    const run = async () => {
        try {
            await mongoose.connect(MONGODB_URI, {
                dbName: process.env.MONGODB_DB_NAME || "nguyenlien_db",
            });

            console.log("✓ MongoDB connected");
            console.log("DB NAME:", mongoose.connection.name);

            await seedProducts();
        } catch (err) {
            console.error("✗ Product seeding error:", err);
            process.exitCode = 1;
        } finally {
            await mongoose.disconnect();
            console.log("✓ MongoDB disconnected");
        }
    };

    run();
}

module.exports = seedProducts;