const mongoose = require("mongoose");

const Category = require("../modules/categories/category.model");
const Product = require("../modules/products/product.model");
const Variant = require("../modules/products/variant.model");
const VariantUnit = require("../modules/products/variant_unit.model");

const CATEGORY_SLUGS = {
    mango: "tui-bao-trai-xoai",
    pomelo: "tui-bao-trai-buoi",
    guava: "tui-bao-trai-oi",
    dragonFruit: "tui-bao-trai-thanh-long",
    jackfruit: "tui-bao-trai-mit",
    grape: "tui-bao-trai-nho",
    longanLychee: "tui-bao-nhan-vai",
    banana: "tui-bao-trai-chuoi",
    custardApple: "tui-bao-trai-na-mang-cau",
    longVegetable: "tui-bao-rau-cu-qua-dai",
};

const productsData = [
    {
        name: "White non-woven mango bag 20x27cm",
        slug: "tui-bao-trai-xoai-vai-khong-det-trang-20x27cm",
        category_slug: CATEGORY_SLUGS.mango,
        brand: "Nguyen Lien",
        short_description: "Regular mango bags, with drawstring, suitable for growing mangoes.",
        description: "The product is used to cover mangoes in the garden, helping to limit insects, dust and reduce scratches on the fruit's skin. White non-woven fabric, breathable, easy to use.",
        keywords: ["tui bao xoai", "bao trai xoai", "vai khong det", "tui day rut"],
        base_price: 45000,
        size_a: "20x27cm",
        size_b: "25x30cm",
        fabric_a: "White non-woven fabric",
        fabric_b: "Thick non-woven fabric",
        stock_a: 6000,
        stock_b: 4200,
        sold_count: 135,
        rating_avg: 4.7,
        rating_count: 31,
    },
    {
        name: "Taiwan mango bag, large size 25x35cm",
        slug: "tui-bao-trai-xoai-dai-loan-size-lon-25x35cm",
        category_slug: CATEGORY_SLUGS.mango,
        brand: "Nguyen Lien",
        short_description: "Large mango bag, suitable for Taiwanese mangoes, sand mangoes and large mangoes.",
        description: "Large mango bag line, used for mango varieties with long or strongly growing fruit. Can be used in small to medium scale production gardens.",
        keywords: ["tui bao xoai lon", "xoai dai loan", "xoai cat", "tui xoai"],
        base_price: 52000,
        size_a: "25x35cm",
        size_b: "28x38cm",
        fabric_a: "White non-woven fabric",
        fabric_b: "2-layer non-woven fabric",
        stock_a: 5000,
        stock_b: 3500,
        sold_count: 89,
        rating_avg: 4.6,
        rating_count: 18,
    },
    {
        name: "Drawstring breathable mesh mango bag",
        slug: "tui-bao-xoai-luoi-thoang-khi-day-rut",
        category_slug: CATEGORY_SLUGS.mango,
        brand: "Farm Bag",
        short_description: "Mesh mango bags, breathable, easy to observe the fruit.",
        description: "Mesh bags are suitable for fruit packaging but still require ventilation and the ability to observe fruit condition during care.",
        keywords: ["tui luoi xoai", "tui bao xoai", "tui thoang khi", "day rut"],
        base_price: 39000,
        size_a: "20x30cm",
        size_b: "25x35cm",
        fabric_a: "White plastic mesh",
        fabric_b: "Thick mesh",
        stock_a: 7200,
        stock_b: 4600,
        sold_count: 76,
        rating_avg: 4.5,
        rating_count: 15,
    },
    {
        name: "Mango yellow paper sun protection bag",
        slug: "tui-bao-xoai-giay-vang-chong-nang",
        category_slug: CATEGORY_SLUGS.mango,
        brand: "Green Farm",
        short_description: "Mango paper bags, suitable for sunny areas.",
        description: "Paper bags help cover the fruit surface, suitable for gardens that need to limit direct sunlight impacting the fruit during some stages of development.",
        keywords: ["tui giay xoai", "bao xoai giay", "chong nang", "tui bao trai"],
        base_price: 48000,
        size_a: "20x28cm",
        size_b: "25x35cm",
        fabric_a: "Yellow kraft paper",
        fabric_b: "2-layer kraft paper",
        stock_a: 3000,
        stock_b: 2200,
        sold_count: 42,
        rating_avg: 4.3,
        rating_count: 9,
    },
    {
        name: "Non-woven grapefruit bag 30x35cm",
        slug: "tui-bao-trai-buoi-vai-khong-det-30x35cm",
        category_slug: CATEGORY_SLUGS.pomelo,
        brand: "Nguyen Lien",
        short_description: "Large size grapefruit bag, suitable for growing grapefruit.",
        description: "Grapefruit bags help protect the fruit from insects and limit scratches on the peel surface. Large size, easy to handle when bagging fruit in the garden.",
        keywords: ["tui bao buoi", "bao trai buoi", "tui size lon", "vai khong det"],
        base_price: 68000,
        size_a: "30x35cm",
        size_b: "35x40cm",
        fabric_a: "White non-woven fabric",
        fabric_b: "Thick non-woven fabric",
        stock_a: 4200,
        stock_b: 2800,
        sold_count: 116,
        rating_avg: 4.8,
        rating_count: 26,
    },
    {
        name: "Large size green leather grapefruit bag",
        slug: "tui-bao-buoi-da-xanh-size-dai",
        category_slug: CATEGORY_SLUGS.pomelo,
        brand: "Nguyen Lien",
        short_description: "Large green leather grapefruit bag, suitable for large fruits.",
        description: "The product is suitable for green-skinned grapefruit, five whip grapefruit and other large sized fruits. The bag mouth is wide, easy to pull out the fixed strap.",
        keywords: ["buoi da xanh", "tui bao buoi", "tui bao trai lon", "tui day rut"],
        base_price: 76000,
        size_a: "35x40cm",
        size_b: "40x45cm",
        fabric_a: "Thick non-woven fabric",
        fabric_b: "2-layer non-woven fabric",
        stock_a: 3200,
        stock_b: 1800,
        sold_count: 72,
        rating_avg: 4.6,
        rating_count: 17,
    },
    {
        name: "Breathable grapefruit mesh bag",
        slug: "tui-luoi-bao-buoi-thoang-khi",
        category_slug: CATEGORY_SLUGS.pomelo,
        brand: "Farm Bag",
        short_description: "Mesh bag for grapefruit, breathable, suitable for gardens that need to observe fruit.",
        description: "Mesh bags have high ventilation, suitable for the need to protect fruit, but you still need to observe the color and size of fruit during care.",
        keywords: ["tui luoi buoi", "bao buoi", "thoang khi", "tui bao trai cay"],
        base_price: 59000,
        size_a: "30x35cm",
        size_b: "35x40cm",
        fabric_a: "White plastic mesh",
        fabric_b: "Thick mesh",
        stock_a: 5000,
        stock_b: 3300,
        sold_count: 55,
        rating_avg: 4.4,
        rating_count: 12,
    },
    {
        name: "Non-woven guava fruit bag 15x20cm",
        slug: "tui-bao-trai-oi-vai-khong-det-15x20cm",
        category_slug: CATEGORY_SLUGS.guava,
        brand: "Nguyen Lien",
        short_description: "Universal guava bag, compact, easy to use.",
        description: "Guava fruit bags help limit yellow flies, insects and dirt. The size is suitable for many popular guava varieties.",
        keywords: ["tui bao oi", "bao trai oi", "ruoi vang", "vai khong det"],
        base_price: 32000,
        size_a: "15x20cm",
        size_b: "18x22cm",
        fabric_a: "White non-woven fabric",
        fabric_b: "Thick non-woven fabric",
        stock_a: 9000,
        stock_b: 6600,
        sold_count: 210,
        rating_avg: 4.8,
        rating_count: 49,
    },
    {
        name: "Red guava drawstring bag",
        slug: "tui-bao-oi-ruot-do-day-rut",
        category_slug: CATEGORY_SLUGS.guava,
        brand: "Nguyen Lien",
        short_description: "Guava bag with drawstring, suitable for red guava and pear guava.",
        description: "A line of guava bags for gardeners who need quick work. The drawstring helps fix the bag mouth better when hanging on a branch.",
        keywords: ["oi ruot do", "tui bao oi", "tui day rut", "bao trai cay"],
        base_price: 35000,
        size_a: "16x22cm",
        size_b: "18x25cm",
        fabric_a: "White non-woven fabric",
        fabric_b: "2-layer non-woven fabric",
        stock_a: 8500,
        stock_b: 5200,
        sold_count: 146,
        rating_avg: 4.7,
        rating_count: 34,
    },
    {
        name: "Anti-scratch guava mesh foam bag",
        slug: "tui-xop-luoi-bao-oi-chong-tray",
        category_slug: CATEGORY_SLUGS.guava,
        brand: "Green Farm",
        short_description: "Mesh foam bag for guava, helps prevent scratches on the fruit's skin.",
        description: "Soft mesh foam bag, suitable for guava fruit that needs to limit collisions and scratches during the growing stage near harvest.",
        keywords: ["tui xop luoi", "bao oi", "chong tray", "tui bao trai"],
        base_price: 42000,
        size_a: "15x20cm",
        size_b: "18x22cm",
        fabric_a: "White mesh foam",
        fabric_b: "Thick mesh foam",
        stock_a: 5600,
        stock_b: 4100,
        sold_count: 64,
        rating_avg: 4.5,
        rating_count: 13,
    },
    {
        name: "Non-woven dragon fruit bag 25x30cm",
        slug: "tui-bao-thanh-long-vai-khong-det-25x30cm",
        category_slug: CATEGORY_SLUGS.dragonFruit,
        brand: "Nguyen Lien",
        short_description: "Dragon fruit bag, medium size, easy to handle.",
        description: "Dragon fruit bags help protect the fruit during the growing process, limiting dust, insects and surface scratches.",
        keywords: ["tui bao thanh long", "bao thanh long", "vai khong det", "tui bao trai"],
        base_price: 50000,
        size_a: "25x30cm",
        size_b: "28x35cm",
        fabric_a: "White non-woven fabric",
        fabric_b: "Thick non-woven fabric",
        stock_a: 4800,
        stock_b: 3400,
        sold_count: 98,
        rating_avg: 4.6,
        rating_count: 20,
    },
    {
        name: "Large red dragon fruit bag",
        slug: "tui-bao-thanh-long-ruot-do-size-lon",
        category_slug: CATEGORY_SLUGS.dragonFruit,
        brand: "Farm Bag",
        short_description: "Large size dragon fruit bags for strong fruit growth.",
        description: "Suitable for red-fleshed dragon fruit or large sized fruit. The material is airy and easy to pull out of the bag.",
        keywords: ["thanh long ruot do", "tui bao thanh long", "size lon", "day rut"],
        base_price: 56000,
        size_a: "28x35cm",
        size_b: "30x40cm",
        fabric_a: "White non-woven fabric",
        fabric_b: "2-layer non-woven fabric",
        stock_a: 3900,
        stock_b: 2600,
        sold_count: 73,
        rating_avg: 4.4,
        rating_count: 14,
    },
    {
        name: "Dust-proof dragon fruit paper bag",
        slug: "tui-giay-bao-thanh-long-chong-bui",
        category_slug: CATEGORY_SLUGS.dragonFruit,
        brand: "Green Farm",
        short_description: "Dragon fruit paper bag, suitable for dust protection and light sunlight.",
        description: "Paper bags for dragon fruits, suitable for gardens that need to protect the fruit surface and reduce environmental impact.",
        keywords: ["tui giay thanh long", "bao thanh long", "chong bui", "tui giay"],
        base_price: 47000,
        size_a: "25x30cm",
        size_b: "28x35cm",
        fabric_a: "Yellow kraft paper",
        fabric_b: "2-layer kraft paper",
        stock_a: 2600,
        stock_b: 1900,
        sold_count: 36,
        rating_avg: 4.2,
        rating_count: 8,
    },
    {
        name: "Non-woven jackfruit bag 45x55cm",
        slug: "tui-bao-trai-mit-vai-khong-det-45x55cm",
        category_slug: CATEGORY_SLUGS.jackfruit,
        brand: "Nguyen Lien",
        short_description: "Large jackfruit bags, suitable for large and heavy fruits.",
        description: "Jackfruit bags are large in size, suitable for large fruits. Thicker material for increased durability when used in the garden.",
        keywords: ["tui bao mit", "bao trai mit", "tui size dai", "vai khong det"],
        base_price: 98000,
        size_a: "45x55cm",
        size_b: "50x60cm",
        fabric_a: "Thick non-woven fabric",
        fabric_b: "2-layer non-woven fabric",
        stock_a: 1600,
        stock_b: 1100,
        sold_count: 48,
        rating_avg: 4.7,
        rating_count: 11,
    },
    {
        name: "Sturdy drawstring Thai jackfruit bag",
        slug: "tui-bao-mit-thai-day-rut-chac-chan",
        category_slug: CATEGORY_SLUGS.jackfruit,
        brand: "Nguyen Lien",
        short_description: "Thai jackfruit bag, wide mouth, strong drawstring.",
        description: "Used for Thai jackfruit and other large jackfruits. The drawstring design helps secure the bag as the fruit grows.",
        keywords: ["mit thai", "tui bao mit", "day rut", "tui trai lon"],
        base_price: 108000,
        size_a: "50x60cm",
        size_b: "55x65cm",
        fabric_a: "Thick non-woven fabric",
        fabric_b: "2-layer non-woven fabric",
        stock_a: 1400,
        stock_b: 900,
        sold_count: 39,
        rating_avg: 4.6,
        rating_count: 10,
    },
    {
        name: "Breathable mesh bag for jackfruit",
        slug: "tui-luoi-bao-mit-thoang-khi",
        category_slug: CATEGORY_SLUGS.jackfruit,
        brand: "Farm Bag",
        short_description: "Jackfruit mesh bag, breathable, large size.",
        description: "Suitable for gardens that need large fruit bags but still maintain high ventilation. Easy to observe the left status.",
        keywords: ["tui luoi mit", "bao mit", "thoang khi", "tui lon"],
        base_price: 89000,
        size_a: "45x55cm",
        size_b: "50x60cm",
        fabric_a: "White plastic mesh",
        fabric_b: "Thick mesh",
        stock_a: 1700,
        stock_b: 1200,
        sold_count: 27,
        rating_avg: 4.3,
        rating_count: 7,
    },
    {
        name: "Non-woven grape bunch bag 20x30cm",
        slug: "tui-bao-chum-nho-vai-khong-det-20x30cm",
        category_slug: CATEGORY_SLUGS.grape,
        brand: "Nguyen Lien",
        short_description: "Grape bunch bag, suitable for bunch packing.",
        description: "Bags for grapes or small fruits that grow in clusters. Medium size, easy to pack and remove.",
        keywords: ["tui bao nho", "bao chum nho", "tui bao chum", "vai khong det"],
        base_price: 41000,
        size_a: "20x30cm",
        size_b: "25x35cm",
        fabric_a: "White non-woven fabric",
        fabric_b: "Thick non-woven fabric",
        stock_a: 6200,
        stock_b: 4400,
        sold_count: 57,
        rating_avg: 4.5,
        rating_count: 13,
    },
    {
        name: "Anti-insect paper bag for grapes",
        slug: "tui-giay-bao-chum-nho-chong-con-trung",
        category_slug: CATEGORY_SLUGS.grape,
        brand: "Green Farm",
        short_description: "Paper bags for grapes, good coverage, suitable for wrapping in bunches.",
        description: "A line of paper bags for grapes, helping to shield and limit insects from direct contact with the fruit.",
        keywords: ["tui giay nho", "bao chum nho", "chong con trung", "tui bao"],
        base_price: 45000,
        size_a: "20x30cm",
        size_b: "25x35cm",
        fabric_a: "Yellow kraft paper",
        fabric_b: "2-layer kraft paper",
        stock_a: 2800,
        stock_b: 1900,
        sold_count: 31,
        rating_avg: 4.2,
        rating_count: 6,
    },
    {
        name: "Breathable grape mesh bag",
        slug: "tui-luoi-bao-chum-nho-thoang-khi",
        category_slug: CATEGORY_SLUGS.grape,
        brand: "Farm Bag",
        short_description: "Grape mesh bag, light, breathable.",
        description: "Mesh bags for grapes or small bunches of fruit. Suitable when high ventilation and easy visibility are needed.",
        keywords: ["tui luoi nho", "bao chum nho", "thoang khi", "tui luoi"],
        base_price: 36000,
        size_a: "18x28cm",
        size_b: "22x32cm",
        fabric_a: "White plastic mesh",
        fabric_b: "Fine mesh",
        stock_a: 5400,
        stock_b: 3800,
        sold_count: 44,
        rating_avg: 4.4,
        rating_count: 9,
    },
    {
        name: "Non-woven fabric label bag 25x35cm",
        slug: "tui-bao-nhan-vai-khong-det-25x35cm",
        category_slug: CATEGORY_SLUGS.longanLychee,
        brand: "Nguyen Lien",
        short_description: "Longan bags in bunches, suitable for longan gardens.",
        description: "Longan bag helps protect fruit bunches from insects and dirt. Good for canoe longan, pepper longan and other popular longan varieties.",
        keywords: ["tui bao nhan", "bao chum nhan", "nhan vai", "vai khong det"],
        base_price: 43000,
        size_a: "25x35cm",
        size_b: "30x40cm",
        fabric_a: "White non-woven fabric",
        fabric_b: "Thick non-woven fabric",
        stock_a: 6400,
        stock_b: 4600,
        sold_count: 86,
        rating_avg: 4.6,
        rating_count: 19,
    },
    {
        name: "Lychee bags in bunches",
        slug: "tui-bao-trai-vai-theo-chum",
        category_slug: CATEGORY_SLUGS.longanLychee,
        brand: "Nguyen Lien",
        short_description: "Lychee fruit bag, suitable for fruit bunches.",
        description: "Product used for lychees and other small fruits that grow in clusters. Lightweight design, easy to handle when covering many bunches on the tree.",
        keywords: ["tui bao vai", "bao chum vai", "tui bao trai vai", "chum trai"],
        base_price: 44000,
        size_a: "25x35cm",
        size_b: "30x40cm",
        fabric_a: "White non-woven fabric",
        fabric_b: "2-layer non-woven fabric",
        stock_a: 5200,
        stock_b: 3100,
        sold_count: 52,
        rating_avg: 4.5,
        rating_count: 12,
    },
    {
        name: "Mesh bag with breathable fabric labels",
        slug: "tui-luoi-bao-nhan-vai-thoang-khi",
        category_slug: CATEGORY_SLUGS.longanLychee,
        brand: "Farm Bag",
        short_description: "Mesh bag with labels and fabric, suitable for small bunches of fruit.",
        description: "Breathable mesh bag, used for longan, lychee or fruits that grow in clusters that need to be observed regularly.",
        keywords: ["tui luoi nhan", "tui luoi vai", "bao chum", "thoang khi"],
        base_price: 37000,
        size_a: "25x35cm",
        size_b: "30x40cm",
        fabric_a: "White plastic mesh",
        fabric_b: "Fine mesh",
        stock_a: 5900,
        stock_b: 4200,
        sold_count: 33,
        rating_avg: 4.3,
        rating_count: 8,
    },
    {
        name: "Non-woven banana bag 60x90cm",
        slug: "tui-bao-buong-chuoi-vai-khong-det-60x90cm",
        category_slug: CATEGORY_SLUGS.banana,
        brand: "Nguyen Lien",
        short_description: "Long size banana bunch bag.",
        description: "The banana bud bag helps protect the fruit chamber during development. Long size, suitable for medium banana bunches.",
        keywords: ["tui bao chuoi", "bao buong chuoi", "tui dai", "vai khong det"],
        base_price: 115000,
        size_a: "60x90cm",
        size_b: "70x100cm",
        fabric_a: "White non-woven fabric",
        fabric_b: "Thick non-woven fabric",
        stock_a: 1300,
        stock_b: 900,
        sold_count: 61,
        rating_avg: 4.7,
        rating_count: 14,
    },
    {
        name: "Banana bag, large size 80x120cm",
        slug: "tui-bao-buong-chuoi-size-dai-80x120cm",
        category_slug: CATEGORY_SLUGS.banana,
        brand: "Nguyen Lien",
        short_description: "Large sized banana bag, suitable for large rooms.",
        description: "Large banana bag line, used for large bunches of bananas or gardens that need extensive coverage.",
        keywords: ["tui bao chuoi dai", "bao buong chuoi", "size dai", "chuoi"],
        base_price: 145000,
        size_a: "80x120cm",
        size_b: "90x130cm",
        fabric_a: "Thick non-woven fabric",
        fabric_b: "2-layer non-woven fabric",
        stock_a: 900,
        stock_b: 650,
        sold_count: 34,
        rating_avg: 4.5,
        rating_count: 8,
    },
    {
        name: "Breathable banana mesh bag",
        slug: "tui-luoi-bao-buong-chuoi-thoang-khi",
        category_slug: CATEGORY_SLUGS.banana,
        brand: "Farm Bag",
        short_description: "Mesh bag for banana bunches, light and airy.",
        description: "Long mesh bag, suitable for banana gardens that require high ventilation and easy observation of the fruit chamber.",
        keywords: ["tui luoi chuoi", "bao chuoi", "buong chuoi", "thoang khi"],
        base_price: 99000,
        size_a: "60x90cm",
        size_b: "70x100cm",
        fabric_a: "White plastic mesh",
        fabric_b: "Thick mesh",
        stock_a: 1500,
        stock_b: 1000,
        sold_count: 29,
        rating_avg: 4.2,
        rating_count: 7,
    },
    {
        name: "Non-woven custard apple bag 18x25cm",
        slug: "tui-bao-trai-na-vai-khong-det-18x25cm",
        category_slug: CATEGORY_SLUGS.custardApple,
        brand: "Nguyen Lien",
        short_description: "Fruit bag, medium size, drawstring.",
        description: "Bags for custard apple fruit help limit insects' contact with the fruit, suitable for the growing stage of the fruit.",
        keywords: ["tui bao na", "bao trai na", "mang cau", "vai khong det"],
        base_price: 38000,
        size_a: "18x25cm",
        size_b: "20x28cm",
        fabric_a: "White non-woven fabric",
        fabric_b: "Thick non-woven fabric",
        stock_a: 5800,
        stock_b: 3900,
        sold_count: 51,
        rating_avg: 4.5,
        rating_count: 11,
    },
    {
        name: "Large size chewy custard apple bag",
        slug: "tui-bao-mang-cau-dai-size-lon",
        category_slug: CATEGORY_SLUGS.custardApple,
        brand: "Nguyen Lien",
        short_description: "The custard apple bag is tough, suitable for large fruits.",
        description: "Product used for tough custard apples and other fruits with surfaces susceptible to insect attack. Airy, lightweight material.",
        keywords: ["tui bao mang cau", "mang cau dai", "tui size lon", "bao trai"],
        base_price: 46000,
        size_a: "22x30cm",
        size_b: "25x35cm",
        fabric_a: "White non-woven fabric",
        fabric_b: "2-layer non-woven fabric",
        stock_a: 4100,
        stock_b: 2700,
        sold_count: 37,
        rating_avg: 4.4,
        rating_count: 9,
    },
    {
        name: "Anti-scratch foam mesh bag",
        slug: "tui-xop-luoi-bao-na-chong-tray",
        category_slug: CATEGORY_SLUGS.custardApple,
        brand: "Green Farm",
        short_description: "Mesh foam bag, helps reduce scratches.",
        description: "Soft mesh foam bag for custard apples, custard apples or fruits with scratchy surfaces. Suitable for light physical protection needs.",
        keywords: ["tui xop luoi", "bao na", "mang cau", "chong tray"],
        base_price: 49000,
        size_a: "18x25cm",
        size_b: "22x30cm",
        fabric_a: "White mesh foam",
        fabric_b: "Thick mesh foam",
        stock_a: 3300,
        stock_b: 2200,
        sold_count: 22,
        rating_avg: 4.1,
        rating_count: 5,
    },
    {
        name: "Non-woven long loofah bag 15x45cm",
        slug: "tui-bao-muop-dai-vai-khong-det-15x45cm",
        category_slug: CATEGORY_SLUGS.longVegetable,
        brand: "Nguyen Lien",
        short_description: "Long loofah bag, suitable for long fruits.",
        description: "Bags for luffa, gourd, squash and other long fruits. Designed to be longer than regular fruit bags.",
        keywords: ["tui bao muop", "tui bao qua dai", "bau bi", "vai khong det"],
        base_price: 53000,
        size_a: "15x45cm",
        size_b: "18x50cm",
        fabric_a: "White non-woven fabric",
        fabric_b: "Thick non-woven fabric",
        stock_a: 4300,
        stock_b: 3000,
        sold_count: 68,
        rating_avg: 4.6,
        rating_count: 15,
    },
    {
        name: "Non-woven fabric sack bag 12x30cm",
        slug: "tui-bao-kho-qua-vai-khong-det-12x30cm",
        category_slug: CATEGORY_SLUGS.longVegetable,
        brand: "Nguyen Lien",
        short_description: "Bitter melon bags are compact and easy to pack.",
        description: "Bitter melon bags help protect the fruit during the growing process. Small size, suitable for medium-length fruits.",
        keywords: ["tui bao kho qua", "kho qua", "qua dai", "vai khong det"],
        base_price: 36000,
        size_a: "12x30cm",
        size_b: "15x35cm",
        fabric_a: "White non-woven fabric",
        fabric_b: "Thick non-woven fabric",
        stock_a: 6500,
        stock_b: 4700,
        sold_count: 74,
        rating_avg: 4.5,
        rating_count: 16,
    },
    {
        name: "Long size maternity bag",
        slug: "tui-bao-bau-bi-size-dai",
        category_slug: CATEGORY_SLUGS.longVegetable,
        brand: "Farm Bag",
        short_description: "The pregnancy bag is long and wide.",
        description: "This line of bags is suitable for gourds, squash, luffa and long-shaped fruits and vegetables. Easy to use in the vegetable garden.",
        keywords: ["tui bao bau", "tui bao bi", "qua dai", "rau cu qua"],
        base_price: 58000,
        size_a: "18x50cm",
        size_b: "20x60cm",
        fabric_a: "White non-woven fabric",
        fabric_b: "2-layer non-woven fabric",
        stock_a: 3600,
        stock_b: 2400,
        sold_count: 41,
        rating_avg: 4.3,
        rating_count: 9,
    },
    {
        name: "Mini mango bag 18x25cm",
        slug: "tui-bao-xoai-mini-18x25cm",
        category_slug: CATEGORY_SLUGS.mango,
        brand: "Nguyen Lien",
        short_description: "Mini mango bags, suitable for small or early stage fruits.",
        description: "Small sized mango bags, used when the fruit is still small or for medium-sized mango varieties.",
        keywords: ["tui bao xoai mini", "xoai nho", "bao xoai", "tui nho"],
        base_price: 34000,
        size_a: "18x25cm",
        size_b: "20x27cm",
        fabric_a: "White non-woven fabric",
        fabric_b: "White plastic mesh",
        stock_a: 7000,
        stock_b: 5100,
        sold_count: 63,
        rating_avg: 4.4,
        rating_count: 13,
    },
    {
        name: "Kraft paper grapefruit bag 35x40cm",
        slug: "tui-bao-buoi-giay-kraft-35x40cm",
        category_slug: CATEGORY_SLUGS.pomelo,
        brand: "Green Farm",
        short_description: "Kraft paper bag for grapefruit, good coverage.",
        description: "Kraft paper bags for grapefruits and large fruits, suitable for light and dust protection needs.",
        keywords: ["tui giay buoi", "giay kraft", "bao buoi", "tui trai lon"],
        base_price: 72000,
        size_a: "35x40cm",
        size_b: "40x45cm",
        fabric_a: "Yellow kraft paper",
        fabric_b: "2-layer kraft paper",
        stock_a: 2300,
        stock_b: 1500,
        sold_count: 21,
        rating_avg: 4.1,
        rating_count: 5,
    },
    {
        name: "Mini guava bag 12x18cm",
        slug: "tui-bao-oi-mini-12x18cm",
        category_slug: CATEGORY_SLUGS.guava,
        brand: "Nguyen Lien",
        short_description: "Small guava bags, used for young fruits or small guava varieties.",
        description: "Compact size, suitable for small guavas or young guavas.",
        keywords: ["tui bao oi mini", "oi non", "tui nho", "bao oi"],
        base_price: 28000,
        size_a: "12x18cm",
        size_b: "15x20cm",
        fabric_a: "White non-woven fabric",
        fabric_b: "Fine mesh",
        stock_a: 7800,
        stock_b: 5300,
        sold_count: 59,
        rating_avg: 4.3,
        rating_count: 12,
    },
    {
        name: "White mesh dragon fruit bag",
        slug: "tui-bao-thanh-long-luoi-trang",
        category_slug: CATEGORY_SLUGS.dragonFruit,
        brand: "Farm Bag",
        short_description: "White mesh bag for dragon fruit, breathable.",
        description: "Used for dragon fruits that need high ventilation, easy to observe the color and size of the fruit.",
        keywords: ["tui luoi thanh long", "bao thanh long", "luoi trang", "thoang khi"],
        base_price: 43000,
        size_a: "25x30cm",
        size_b: "28x35cm",
        fabric_a: "White plastic mesh",
        fabric_b: "Thick mesh",
        stock_a: 3900,
        stock_b: 2600,
        sold_count: 18,
        rating_avg: 4.0,
        rating_count: 4,
    },
    {
        name: "Large size kraft paper jackfruit bag",
        slug: "tui-bao-mit-giay-kraft-size-lon",
        category_slug: CATEGORY_SLUGS.jackfruit,
        brand: "Green Farm",
        short_description: "Kraft paper bag for jackfruit, large size.",
        description: "Kraft paper bags are used for jackfruit or very large fruits, helping to cover dust and light sunlight.",
        keywords: ["tui giay mit", "giay kraft", "bao mit", "tui size lon"],
        base_price: 95000,
        size_a: "45x55cm",
        size_b: "50x60cm",
        fabric_a: "Yellow kraft paper",
        fabric_b: "2-layer kraft paper",
        stock_a: 1100,
        stock_b: 750,
        sold_count: 12,
        rating_avg: 4.0,
        rating_count: 3,
        status: "INACTIVE",
    },
    {
        name: "Mini grape bag 18x25cm",
        slug: "tui-bao-chum-nho-mini-18x25cm",
        category_slug: CATEGORY_SLUGS.grape,
        brand: "Nguyen Lien",
        short_description: "Bags for small bunches, suitable for medium bunches.",
        description: "Small sized grape bunch bags, suitable for medium fruit bunches or test gardens.",
        keywords: ["tui bao nho mini", "chum nho", "tui nho", "bao nho"],
        base_price: 32000,
        size_a: "18x25cm",
        size_b: "20x30cm",
        fabric_a: "White non-woven fabric",
        fabric_b: "Fine mesh",
        stock_a: 4200,
        stock_b: 3000,
        sold_count: 24,
        rating_avg: 4.2,
        rating_count: 5,
    },
    {
        name: "Kraft paper label bag",
        slug: "tui-bao-nhan-giay-kraft",
        category_slug: CATEGORY_SLUGS.longanLychee,
        brand: "Green Farm",
        short_description: "Kraft paper bag containing bunches of longans.",
        description: "Kraft paper bags are used for labels, fabrics or small fruit bunches that need good coverage.",
        keywords: ["tui giay nhan", "bao chum nhan", "giay kraft", "nhan vai"],
        base_price: 42000,
        size_a: "25x35cm",
        size_b: "30x40cm",
        fabric_a: "Yellow kraft paper",
        fabric_b: "2-layer kraft paper",
        stock_a: 1900,
        stock_b: 1200,
        sold_count: 14,
        rating_avg: 4.1,
        rating_count: 4,
    },
    {
        name: "Kraft banana bag",
        slug: "tui-bao-chuoi-giay-kraft",
        category_slug: CATEGORY_SLUGS.banana,
        brand: "Green Farm",
        short_description: "Kraft paper bags for banana bunches.",
        description: "Used for banana bunches that need to be protected from dust and light sunlight. Long size suitable for hanging in the garden.",
        keywords: ["tui giay chuoi", "bao buong chuoi", "giay kraft", "tui dai"],
        base_price: 125000,
        size_a: "60x90cm",
        size_b: "70x100cm",
        fabric_a: "Yellow kraft paper",
        fabric_b: "2-layer kraft paper",
        stock_a: 800,
        stock_b: 500,
        sold_count: 9,
        rating_avg: 3.9,
        rating_count: 3,
        status: "INACTIVE",
    },
    {
        name: "Bag of soursop bags 30x40cm",
        slug: "tui-bao-mang-cau-xiem-30x40cm",
        category_slug: CATEGORY_SLUGS.custardApple,
        brand: "Nguyen Lien",
        short_description: "Large bag of soursop bags.",
        description: "Soursop bags, larger in size than regular soursop bags, suitable for large fruits.",
        keywords: ["mang cau xiem", "tui bao mang cau", "tui size lon", "bao trai"],
        base_price: 62000,
        size_a: "30x40cm",
        size_b: "35x45cm",
        fabric_a: "White non-woven fabric",
        fabric_b: "Thick non-woven fabric",
        stock_a: 2400,
        stock_b: 1600,
        sold_count: 19,
        rating_avg: 4.2,
        rating_count: 5,
    },
    {
        name: "Cucumber bag 10x28cm",
        slug: "tui-bao-dua-leo-10x28cm",
        category_slug: CATEGORY_SLUGS.longVegetable,
        brand: "Nguyen Lien",
        short_description: "Small, long cucumber bag.",
        description: "Bags of cucumbers and small long fruits. Suitable for vegetable gardens that require fruit bags to limit insects.",
        keywords: ["tui bao dua leo", "dua leo", "qua dai", "tui nho"],
        base_price: 30000,
        size_a: "10x28cm",
        size_b: "12x32cm",
        fabric_a: "White non-woven fabric",
        fabric_b: "Fine mesh",
        stock_a: 6200,
        stock_b: 4400,
        sold_count: 47,
        rating_avg: 4.4,
        rating_count: 10,
    },
    {
        name: "Premium 2-layer mango bag",
        slug: "tui-bao-xoai-cao-cap-2-lop",
        category_slug: CATEGORY_SLUGS.mango,
        brand: "Nguyen Lien Premium",
        short_description: "2-layer mango bag, thicker than the popular line.",
        description: "High-quality mango bag line, thicker material, suitable for gardeners who need more durability when used outdoors.",
        keywords: ["tui bao xoai cao cap", "2 lop", "vai khong det", "tui day"],
        base_price: 66000,
        size_a: "25x35cm",
        size_b: "28x38cm",
        fabric_a: "2-layer non-woven fabric",
        fabric_b: "Thick non-woven fabric",
        stock_a: 2600,
        stock_b: 1800,
        sold_count: 26,
        rating_avg: 4.5,
        rating_count: 6,
    },
    {
        name: "Premium 2-layer grapefruit bag",
        slug: "tui-bao-buoi-cao-cap-2-lop",
        category_slug: CATEGORY_SLUGS.pomelo,
        brand: "Nguyen Lien Premium",
        short_description: "2-layer grapefruit bag, large size.",
        description: "High-end grapefruit bag line, suitable for large fruits and needs better protection than the popular line.",
        keywords: ["tui bao buoi cao cap", "2 lop", "tui size lon", "buoi"],
        base_price: 88000,
        size_a: "35x40cm",
        size_b: "40x45cm",
        fabric_a: "2-layer non-woven fabric",
        fabric_b: "Thick non-woven fabric",
        stock_a: 1900,
        stock_b: 1200,
        sold_count: 18,
        rating_avg: 4.4,
        rating_count: 5,
    },
    {
        name: "Premium 2-layer guava bag",
        slug: "tui-bao-oi-cao-cap-2-lop",
        category_slug: CATEGORY_SLUGS.guava,
        brand: "Nguyen Lien Premium",
        short_description: "2-layer guava bag, stronger than the regular line.",
        description: "High-quality guava bag line, suitable for gardeners who need thicker bags and better shape retention.",
        keywords: ["tui bao oi cao cap", "2 lop", "bao oi", "tui day"],
        base_price: 46000,
        size_a: "16x22cm",
        size_b: "18x25cm",
        fabric_a: "2-layer non-woven fabric",
        fabric_b: "Thick non-woven fabric",
        stock_a: 3300,
        stock_b: 2300,
        sold_count: 22,
        rating_avg: 4.5,
        rating_count: 5,
    },
    {
        name: "High quality dragon fruit bag",
        slug: "tui-bao-thanh-long-cao-cap",
        category_slug: CATEGORY_SLUGS.dragonFruit,
        brand: "Nguyen Lien Premium",
        short_description: "Thick material dragon fruit bag.",
        description: "Line of dragon fruit bags made of thick material, suitable for more durable use in the garden.",
        keywords: ["tui bao thanh long cao cap", "2 lop", "thanh long", "tui day"],
        base_price: 62000,
        size_a: "28x35cm",
        size_b: "30x40cm",
        fabric_a: "2-layer non-woven fabric",
        fabric_b: "Thick non-woven fabric",
        stock_a: 2100,
        stock_b: 1500,
        sold_count: 13,
        rating_avg: 4.2,
        rating_count: 4,
    },
    {
        name: "Large-sized premium jackfruit bag",
        slug: "tui-bao-mit-cao-cap-size-dai",
        category_slug: CATEGORY_SLUGS.jackfruit,
        brand: "Nguyen Lien Premium",
        short_description: "High quality jackfruit bag, large size.",
        description: "Large size jackfruit bags, thick material, suitable for large fruits and longer hanging time in the garden.",
        keywords: ["tui bao mit cao cap", "size dai", "mit", "tui day"],
        base_price: 125000,
        size_a: "55x65cm",
        size_b: "60x70cm",
        fabric_a: "2-layer non-woven fabric",
        fabric_b: "Thick non-woven fabric",
        stock_a: 700,
        stock_b: 450,
        sold_count: 8,
        rating_avg: 4.1,
        rating_count: 3,
        status: "INACTIVE",
    },
    {
        name: "High quality dustproof grape bag",
        slug: "tui-bao-nho-cao-cap-chong-bui",
        category_slug: CATEGORY_SLUGS.grape,
        brand: "Nguyen Lien Premium",
        short_description: "High quality grape bags, good dust cover.",
        description: "Grape bunch bags are made of thicker material, suitable for gardens that need to better protect fruit bunches.",
        keywords: ["tui bao nho cao cap", "chong bui", "nho", "bao chum"],
        base_price: 52000,
        size_a: "22x32cm",
        size_b: "25x35cm",
        fabric_a: "2-layer non-woven fabric",
        fabric_b: "Thick non-woven fabric",
        stock_a: 1900,
        stock_b: 1300,
        sold_count: 11,
        rating_avg: 4.0,
        rating_count: 3,
    },
    {
        name: "High quality fabric label bag",
        slug: "tui-bao-nhan-vai-cao-cap",
        category_slug: CATEGORY_SLUGS.longanLychee,
        brand: "Nguyen Lien Premium",
        short_description: "Label bag, high quality fabric, thick material.",
        description: "Thick fabric label bag, used for gardens that need to protect fruit bunches better.",
        keywords: ["tui bao nhan cao cap", "tui bao vai", "bao chum", "2 lop"],
        base_price: 54000,
        size_a: "30x40cm",
        size_b: "35x45cm",
        fabric_a: "2-layer non-woven fabric",
        fabric_b: "Thick non-woven fabric",
        stock_a: 1700,
        stock_b: 1100,
        sold_count: 10,
        rating_avg: 4.0,
        rating_count: 3,
    },
    {
        name: "Premium 2-layer banana bag",
        slug: "tui-bao-chuoi-cao-cap-2-lop",
        category_slug: CATEGORY_SLUGS.banana,
        brand: "Nguyen Lien Premium",
        short_description: "High quality banana bags, thick material.",
        description: "Banana bags are made of thick material, suitable for large rooms and can be used in the garden longer.",
        keywords: ["tui bao chuoi cao cap", "2 lop", "buong chuoi", "tui dai"],
        base_price: 165000,
        size_a: "80x120cm",
        size_b: "90x130cm",
        fabric_a: "2-layer non-woven fabric",
        fabric_b: "Thick non-woven fabric",
        stock_a: 520,
        stock_b: 350,
        sold_count: 7,
        rating_avg: 4.0,
        rating_count: 2,
        status: "INACTIVE",
    },
    {
        name: "2-layer luxury condom bag",
        slug: "tui-bao-na-cao-cap-2-lop",
        category_slug: CATEGORY_SLUGS.custardApple,
        brand: "Nguyen Lien Premium",
        short_description: "The bag is made of thick material and has a drawstring.",
        description: "High-quality bag line, suitable for bags that are easily scratched and require thicker bags than the popular line.",
        keywords: ["tui bao na cao cap", "2 lop", "mang cau", "tui day"],
        base_price: 56000,
        size_a: "22x30cm",
        size_b: "25x35cm",
        fabric_a: "2-layer non-woven fabric",
        fabric_b: "Thick non-woven fabric",
        stock_a: 1600,
        stock_b: 1000,
        sold_count: 9,
        rating_avg: 4.1,
        rating_count: 3,
    },
    {
        name: "Premium long fruit and vegetable bags",
        slug: "tui-bao-rau-cu-qua-dai-cao-cap",
        category_slug: CATEGORY_SLUGS.longVegetable,
        brand: "Nguyen Lien Premium",
        short_description: "Long fruit and vegetable bags, thick material.",
        description: "High-quality bag line for luffa, gourd, squash, cucumber, bitter melon and other long fruits.",
        keywords: ["tui bao rau cu", "qua dai", "2 lop", "tui dai"],
        base_price: 69000,
        size_a: "18x50cm",
        size_b: "20x60cm",
        fabric_a: "2-layer non-woven fabric",
        fabric_b: "Thick non-woven fabric",
        stock_a: 1800,
        stock_b: 1200,
        sold_count: 12,
        rating_avg: 4.1,
        rating_count: 3,
        status: "INACTIVE",
    },
];

const toSkuPart = (value) => {
    return value
        .normalize("NFD")
        .replace(/[\u0300-\u036f]/g, "")
        .replace(/\u0111/g, "d")
        .replace(/\u0110/g, "D")
        .toUpperCase()
        .replace(/[^A-Z0-9]+/g, "-")
        .replace(/^-+|-+$/g, "")
        .slice(0, 36);
};

const buildPriceTiers = (basePrice) => {
    return [
        {
            min_qty: 1,
            max_qty: 4,
            unit_price: basePrice,
        },
        {
            min_qty: 5,
            max_qty: 9,
            unit_price: Math.round(basePrice * 0.94),
        },
        {
            min_qty: 10,
            max_qty: null,
            unit_price: Math.round(basePrice * 0.88),
        },
    ];
};

const buildUnits = (basePrice) => {
    return [
        {
            unit_type: "PACK",
            display_name: "Pack of 100",
            pack_size: 100,
            price_tiers: buildPriceTiers(basePrice),
            min_order_qty: 1,
            max_order_qty: null,
            qty_step: 1,
            is_default: true,
            currency: "VND",
        },
        {
            unit_type: "BOX",
            display_name: "Carton of 1000 pieces",
            pack_size: 1000,
            price_tiers: buildPriceTiers(Math.round(basePrice * 9.2)),
            min_order_qty: 1,
            max_order_qty: null,
            qty_step: 1,
            is_default: false,
            currency: "VND",
        },
    ];
};

const buildVariants = (product) => {
    return [
        {
            sku: `NL-${toSkuPart(product.slug)}-A`,
            size: product.size_a,
            fabric_type: product.fabric_a,
            stock: {
                available: product.stock_a,
                reserved: 0,
                sold: product.sold_count || 0,
            },
            units: buildUnits(product.base_price),
        },
        {
            sku: `NL-${toSkuPart(product.slug)}-B`,
            size: product.size_b,
            fabric_type: product.fabric_b,
            stock: {
                available: product.stock_b,
                reserved: 0,
                sold: Math.floor((product.sold_count || 0) * 0.45),
            },
            units: buildUnits(Math.round(product.base_price * 1.18)),
        },
    ];
};

const seedProducts = async () => {
    console.log("== Seeding products ==");

    const categories = await Category.find({
        slug: { $in: Object.values(CATEGORY_SLUGS) },
        status: "ACTIVE",
    }).select("_id slug");

    const categoryMap = new Map(
        categories.map((category) => [category.slug, category._id])
    );

    const missingCategorySlugs = Object.values(CATEGORY_SLUGS).filter(
        (slug) => !categoryMap.has(slug)
    );

    if (missingCategorySlugs.length > 0) {
        throw new Error(
            `Missing categories. Run "npm run seed:categories" first. Missing: ${missingCategorySlugs.join(", ")}`
        );
    }

    for (const item of productsData) {
        const categoryId = categoryMap.get(item.category_slug);

        const existingProduct = await Product.findOne(
            { slug: item.slug },
            null,
            { includeDeleted: true }
        );

        let product;

        const productPayload = {
            name: item.name,
            slug: item.slug,
            category_id: categoryId,
            brand: item.brand,
            short_description: item.short_description,
            description: item.description,
            images: [],
            search_keywords: item.keywords,
            rating_avg: item.rating_avg || 0,
            rating_count: item.rating_count || 0,
            sold_count: item.sold_count || 0,
            status: item.status || "ACTIVE",
            is_deleted: false,
            deleted_at: null,
        };

        if (existingProduct) {
            await Product.updateOne(
                { _id: existingProduct._id },
                { $set: productPayload },
                { runValidators: true }
            );

            product = await Product.findById(existingProduct._id);

            console.log(`↻ Updated product: ${item.slug}`);
        } else {
            product = await Product.create(productPayload);

            console.log(`✓ Created product: ${item.slug}`);
        }

        const variants = buildVariants(item);

        for (const variantData of variants) {
            const existingVariant = await Variant.findOne(
                {
                    product_id: product._id,
                    size: variantData.size,
                    fabric_type: variantData.fabric_type,
                },
                null,
                { includeDeleted: true }
            );

            let variant;

            const variantPayload = {
                product_id: product._id,
                sku: variantData.sku,
                size: variantData.size,
                fabric_type: variantData.fabric_type,
                stock: variantData.stock,
                status: product.status,
                is_deleted: false,
                deleted_at: null,
            };

            if (existingVariant) {
                await Variant.updateOne(
                    { _id: existingVariant._id },
                    { $set: variantPayload },
                    { runValidators: true }
                );

                variant = await Variant.findById(existingVariant._id);

                console.log(`  ↻ Updated variant: ${variantData.sku}`);
            } else {
                variant = await Variant.create(variantPayload);

                console.log(`  ✓ Created variant: ${variantData.sku}`);
            }

            for (const unitData of variantData.units) {
                VariantUnit.validatePriceTiers(unitData.price_tiers);

                const existingUnit = await VariantUnit.findOne({
                    variant_id: variant._id,
                    pack_size: unitData.pack_size,
                });

                const unitPayload = {
                    variant_id: variant._id,
                    unit_type: unitData.unit_type,
                    display_name: unitData.display_name,
                    pack_size: unitData.pack_size,
                    price_tiers: unitData.price_tiers,
                    min_order_qty: unitData.min_order_qty,
                    max_order_qty: unitData.max_order_qty,
                    qty_step: unitData.qty_step,
                    is_default: unitData.is_default,
                    currency: unitData.currency,
                };

                if (existingUnit) {
                    await VariantUnit.updateOne(
                        { _id: existingUnit._id },
                        { $set: unitPayload },
                        { runValidators: true }
                    );

                    console.log(
                        `    ↻ Updated unit: ${unitData.display_name}`
                    );
                } else {
                    await VariantUnit.create(unitPayload);

                    console.log(
                        `    ✓ Created unit: ${unitData.display_name}`
                    );
                }
            }

            await Variant.updatePriceCache(variant._id);
        }

        await Product.updatePriceCache(product._id);
    }

    console.log("✓ Products seeding completed");
};

if (require.main === module) {
    require("dotenv").config();

    const MONGODB_URI = process.env.MONGO_URI;

    if (!MONGODB_URI) {
        throw new Error("Missing MONGO_URI in .env");
    }

    const run = async () => {
        try {
            await mongoose.connect(MONGODB_URI, {
                dbName: process.env.MONGODB_DB_NAME || "nguyenlien_db",
            });

            console.log("✓ MongoDB connected");
            console.log("DB NAME:", mongoose.connection.name);

            await seedProducts();
        } catch (err) {
            console.error("✗ Product seeding error:", err);
            process.exitCode = 1;
        } finally {
            await mongoose.disconnect();
            console.log("✓ MongoDB disconnected");
        }
    };

    run();
}

module.exports = seedProducts;
