export const ROLES = {
    CUSTOMER: 'CUSTOMER',
    VIP: 'VIP',
    MANAGER: 'MANAGER',
    ADMIN: 'ADMIN',
};

export const ADMIN_ENTRY_ROLES = [ROLES.ADMIN, ROLES.MANAGER];
export const ADMIN_ONLY_ROLES = [ROLES.ADMIN];
export const STAFF_ROLES = [ROLES.ADMIN, ROLES.MANAGER];
export const CATALOG_MANAGER_ROLES = STAFF_ROLES;
export const CONTENT_MANAGER_ROLES = STAFF_ROLES;
export const ORDER_MANAGER_ROLES = STAFF_ROLES;
export const SHIPMENT_MANAGER_ROLES = STAFF_ROLES;
export const DISCOUNT_MANAGER_ROLES = STAFF_ROLES;
export const REVIEW_MANAGER_ROLES = STAFF_ROLES;
export const FINANCE_VIEW_ROLES = STAFF_ROLES;
export const FINANCE_ADMIN_ROLES = ADMIN_ONLY_ROLES;
export const SYSTEM_ADMIN_ROLES = ADMIN_ONLY_ROLES;
