export const ROUTES = {
    HOME: '/',
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
    ADMIN: '/admin',
    ADMIN_PRODUCTS: '/admin/products',
    ADMIN_CATEGORIES: '/admin/categories',
    ADMIN_ORDERS: '/admin/orders',
    ADMIN_PAYMENTS: '/admin/payments',
    ADMIN_SHIPMENTS: '/admin/shipments',
    ADMIN_DISCOUNTS: '/admin/discounts',
    ADMIN_BANNERS: '/admin/banners',
    ADMIN_ANNOUNCEMENTS: '/admin/announcements',
    ADMIN_SHOP_INFO: '/admin/shop-info',
    ADMIN_USERS: '/admin/users',
    ADMIN_AUDIT_LOGS: '/admin/audit-logs',
    PRODUCTS: '/products',
    CART: '/cart',
    CHECKOUT: '/checkout',
    ORDERS: '/orders',
    PROFILE: '/profile',
};
