const AUDIT_ACTIONS = {
    AUTH_LOGIN: 'AUTH_LOGIN',
    AUTH_CHANGE_PASSWORD: 'AUTH_CHANGE_PASSWORD',
    AUTH_FORGOT_PASSWORD: 'AUTH_FORGOT_PASSWORD',
    AUTH_RESET_PASSWORD: 'AUTH_RESET_PASSWORD',
    AUTH_REGISTER: 'AUTH_REGISTER',

    UPDATE_USER_PROFILE: 'UPDATE_USER_PROFILE',
    UPDATE_USER_ROLES: 'UPDATE_USER_ROLES',
    UPDATE_USER_STATUS: 'UPDATE_USER_STATUS',
    DELETE_USER_SOFT: 'DELETE_USER_SOFT',

    CREATE_USER_ADDRESS: 'CREATE_USER_ADDRESS',
    UPDATE_USER_ADDRESS: 'UPDATE_USER_ADDRESS',
    DELETE_USER_ADDRESS: 'DELETE_USER_ADDRESS',
    SET_DEFAULT_USER_ADDRESS: 'SET_DEFAULT_USER_ADDRESS',

    CREATE_CATEGORY: 'CREATE_CATEGORY',
    UPDATE_CATEGORY: 'UPDATE_CATEGORY',
    DELETE_CATEGORY_SOFT: 'DELETE_CATEGORY_SOFT',
    DELETE_CATEGORY_HARD: 'DELETE_CATEGORY_HARD',
    RESTORE_CATEGORY: 'RESTORE_CATEGORY',

    CREATE_PAYMENT: 'CREATE_PAYMENT',
    RETRY_PAYMENT: 'RETRY_PAYMENT',
    CANCEL_PAYMENT: 'CANCEL_PAYMENT',
    ADMIN_VERIFY_PAYMENT: 'ADMIN_VERIFY_PAYMENT',
    DELETE_PAYMENT_SOFT: 'DELETE_PAYMENT_SOFT',
    VNPAY_WEBHOOK_PAYMENT: 'VNPAY_WEBHOOK_PAYMENT',
    STRIPE_WEBHOOK_PAYMENT: 'STRIPE_WEBHOOK_PAYMENT',
    PAYPAL_WEBHOOK_PAYMENT: 'PAYPAL_WEBHOOK_PAYMENT',
    PAYMENT_WEBHOOK_AMOUNT_MISMATCH: 'PAYMENT_WEBHOOK_AMOUNT_MISMATCH',
    PAYMENT_WEBHOOK_REJECTED: 'PAYMENT_WEBHOOK_REJECTED',

    CREATE_ORDER: 'CREATE_ORDER',
    CANCEL_ORDER: 'CANCEL_ORDER',
    ADMIN_UPDATE_ORDER_STATUS: 'ADMIN_UPDATE_ORDER_STATUS',
    ADMIN_UPDATE_ORDER: 'ADMIN_UPDATE_ORDER',
    FULFILL_ORDER_ITEMS: 'FULFILL_ORDER_ITEMS',
    RECORD_ORDER_SHIPMENT: 'RECORD_ORDER_SHIPMENT',
    CONFIRM_ORDER_DELIVERY: 'CONFIRM_ORDER_DELIVERY',

    CREATE_SHIPMENT: 'CREATE_SHIPMENT',
    SHIPMENT_WEBHOOK_STATUS: 'SHIPMENT_WEBHOOK_STATUS',
    SHIPMENT_WEBHOOK_REJECTED: 'SHIPMENT_WEBHOOK_REJECTED',
    UPDATE_SHIPMENT_STATUS: 'UPDATE_SHIPMENT_STATUS',
    RECORD_SHIPMENT_FAILURE: 'RECORD_SHIPMENT_FAILURE',
    CANCEL_SHIPMENT: 'CANCEL_SHIPMENT',
    RETRY_SHIPMENT: 'RETRY_SHIPMENT',
    CONFIRM_SHIPMENT_DELIVERY: 'CONFIRM_SHIPMENT_DELIVERY',
    ADMIN_UPDATE_SHIPMENT: 'ADMIN_UPDATE_SHIPMENT',
    DELETE_SHIPMENT_SOFT: 'DELETE_SHIPMENT_SOFT',

    CREATE_PRODUCT: 'CREATE_PRODUCT',
    UPDATE_PRODUCT: 'UPDATE_PRODUCT',
    DELETE_PRODUCT_SOFT: 'DELETE_PRODUCT_SOFT',
    CREATE_VARIANT: 'CREATE_VARIANT',
    UPDATE_VARIANT: 'UPDATE_VARIANT',
    DELETE_VARIANT_SOFT: 'DELETE_VARIANT_SOFT',
    CREATE_VARIANT_UNIT: 'CREATE_VARIANT_UNIT',
    UPDATE_VARIANT_UNIT: 'UPDATE_VARIANT_UNIT',
    DELETE_VARIANT_UNIT: 'DELETE_VARIANT_UNIT',
    RESERVE_VARIANT_STOCK: 'RESERVE_VARIANT_STOCK',
    COMPLETE_VARIANT_SALE: 'COMPLETE_VARIANT_SALE',
    RELEASE_VARIANT_STOCK: 'RELEASE_VARIANT_STOCK',

    CREATE_DISCOUNT: 'CREATE_DISCOUNT',
    BULK_IMPORT_DISCOUNTS: 'BULK_IMPORT_DISCOUNTS',
    UPDATE_DISCOUNT: 'UPDATE_DISCOUNT',
    DELETE_DISCOUNT_SOFT: 'DELETE_DISCOUNT_SOFT',
    REVOKE_DISCOUNT: 'REVOKE_DISCOUNT',
    DUPLICATE_DISCOUNT: 'DUPLICATE_DISCOUNT',
    REDEEM_DISCOUNT: 'REDEEM_DISCOUNT',
};

const ENTITY_TYPES = {
    AUTH: 'AUTH',
    USER: 'USER',
    USER_ADDRESS: 'USER_ADDRESS',
    CATEGORY: 'CATEGORY',
    PRODUCT: 'PRODUCT',
    PAYMENT: 'PAYMENT',
    ORDER: 'ORDER',
    SHIPMENT: 'SHIPMENT',
    DISCOUNT: 'DISCOUNT',
};

const AUDIT_LEVELS = ['INFO', 'IMPORTANT', 'SECURITY'];

module.exports = {
    AUDIT_ACTIONS,
    ENTITY_TYPES,
    AUDIT_LEVELS
};
