const AUDIT_ACTIONS = {
    AUTH_LOGIN: 'AUTH_LOGIN',
    AUTH_CHANGE_PASSWORD: 'AUTH_CHANGE_PASSWORD',
    AUTH_FORGOT_PASSWORD: 'AUTH_FORGOT_PASSWORD',
    AUTH_RESET_PASSWORD: 'AUTH_RESET_PASSWORD',
    AUTH_REGISTER: 'AUTH_REGISTER',

    UPDATE_USER_PROFILE: 'UPDATE_USER_PROFILE',
    UPDATE_USER_ROLES: 'UPDATE_USER_ROLES',
    UPDATE_USER_STATUS: 'UPDATE_USER_STATUS',
    DELETE_USER_SOFT: 'DELETE_USER_SOFT',

    CREATE_USER_ADDRESS: 'CREATE_USER_ADDRESS',
    UPDATE_USER_ADDRESS: 'UPDATE_USER_ADDRESS',
    DELETE_USER_ADDRESS: 'DELETE_USER_ADDRESS',
    SET_DEFAULT_USER_ADDRESS: 'SET_DEFAULT_USER_ADDRESS',

    CREATE_CATEGORY: 'CREATE_CATEGORY',
    UPDATE_CATEGORY: 'UPDATE_CATEGORY',
    DELETE_CATEGORY_SOFT: 'DELETE_CATEGORY_SOFT',
    DELETE_CATEGORY_HARD: 'DELETE_CATEGORY_HARD',
    RESTORE_CATEGORY: 'RESTORE_CATEGORY',

    CREATE_PAYMENT: 'CREATE_PAYMENT',
    RETRY_PAYMENT: 'RETRY_PAYMENT',
    CANCEL_PAYMENT: 'CANCEL_PAYMENT',
    ADMIN_VERIFY_PAYMENT: 'ADMIN_VERIFY_PAYMENT',
    DELETE_PAYMENT_SOFT: 'DELETE_PAYMENT_SOFT',
    VNPAY_WEBHOOK_PAYMENT: 'VNPAY_WEBHOOK_PAYMENT',
    STRIPE_WEBHOOK_PAYMENT: 'STRIPE_WEBHOOK_PAYMENT',
    PAYPAL_WEBHOOK_PAYMENT: 'PAYPAL_WEBHOOK_PAYMENT',
    PAYMENT_WEBHOOK_AMOUNT_MISMATCH: 'PAYMENT_WEBHOOK_AMOUNT_MISMATCH',
    PAYMENT_WEBHOOK_REJECTED: 'PAYMENT_WEBHOOK_REJECTED',
};

const ENTITY_TYPES = {
    AUTH: 'AUTH',
    USER: 'USER',
    USER_ADDRESS: 'USER_ADDRESS',
    CATEGORY: 'CATEGORY',
    PRODUCT: 'PRODUCT',
    PAYMENT: 'PAYMENT',
};

const AUDIT_LEVELS = ['INFO', 'IMPORTANT', 'SECURITY'];

module.exports = {
    AUDIT_ACTIONS,
    ENTITY_TYPES,
    AUDIT_LEVELS
};
