const AUDIT_ACTIONS = {
    UPDATE_USER_PROFILE: 'UPDATE_USER_PROFILE',
    UPDATE_USER_ROLES: 'UPDATE_USER_ROLES',
    UPDATE_USER_STATUS: 'UPDATE_USER_STATUS',
    DELETE_USER_SOFT: 'DELETE_USER_SOFT',
};

const ENTITY_TYPES = {
    USER: 'USER',
    CATEGORY: 'CATEGORY',
    PRODUCT: 'PRODUCT',
};

module.exports = {
    AUDIT_ACTIONS,
    ENTITY_TYPES,
};