const ROLES = {
    ADMIN: 'ADMIN',
    MANAGER: 'MANAGER',
    VIP: 'VIP',
    CUSTOMER: 'CUSTOMER',
};

const ALL_ROLES = Object.values(ROLES);

const ADMIN_ONLY_ROLES = [ROLES.ADMIN];
const STAFF_ROLES = [ROLES.ADMIN, ROLES.MANAGER];
const CATALOG_MANAGER_ROLES = STAFF_ROLES;
const ORDER_MANAGER_ROLES = STAFF_ROLES;
const SHIPMENT_MANAGER_ROLES = STAFF_ROLES;
const DISCOUNT_MANAGER_ROLES = STAFF_ROLES;
const REVIEW_MANAGER_ROLES = STAFF_ROLES;
const FINANCE_VIEW_ROLES = STAFF_ROLES;
const FINANCE_ADMIN_ROLES = ADMIN_ONLY_ROLES;
const SYSTEM_ADMIN_ROLES = ADMIN_ONLY_ROLES;

module.exports = {
    ROLES,
    ALL_ROLES,
    ADMIN_ONLY_ROLES,
    STAFF_ROLES,
    CATALOG_MANAGER_ROLES,
    ORDER_MANAGER_ROLES,
    SHIPMENT_MANAGER_ROLES,
    DISCOUNT_MANAGER_ROLES,
    REVIEW_MANAGER_ROLES,
    FINANCE_VIEW_ROLES,
    FINANCE_ADMIN_ROLES,
    SYSTEM_ADMIN_ROLES,
};
